<?php
$lang = [
    'translation.language' => 'Chinese',
    'translation.translator' => 's1042992',
    'translation.translator.url' => 'https://github/s1042992',
    'translation.last-updated' => 'October 29th 2018',
    'error.page-not-found' => '网页未找到',
    'error.page-not-found.description' => '所需的页面无法找到',
    'error.no-access' => '不可存取',
    'error.no-access.description' => '您无权访问此页面（不再）',
    'error.return-to-home' => '返回主页',
    'error.login.login' => '此用户名或电子邮件地址没有帐户。',
    'error.login.password' => '输入的密码不正确。',
    'error.login.banned' => '此帐户已被禁止。 原因：％1',
    'error.login.blocked' => '登录尝试被阻止。',
    'error.register.username.legnth' => '您的用户名必须至少为3个字符，且不得超过20个字符。',
    'error.register.username.not-available' => '此用戶名不可使用',
    'error.register.password.length' => '您的密码长度必须至少为8个字符。
',
    'error.register.password.dont-match' => '输入的密码不匹配',
    'error.register.email.not-available' => '此电子邮件地址已有一个帐户。',
    'error.register.email.format' => '此电子邮件地址无效。',
    'error.register.blocked' => '此注册尝试被阻止。',
    'general.advertisement' => '广告',
    'general.users-online' => '在线有％1名玩家！',
    'general.welcome' => '欢迎来到％1',
    'general.register-now' => '立即注册％1',
    'general.enter-hotel' => '登入%1!',
    'general.logged-out' => '你已经退出了！ 再见。',
    'general.welcome-back' => '欢迎回来, %1',
    'login' => '登入',
    'login.username-or-email' => '用户名或电子邮件',
    'login.password' => '密码',
    'login.remember-me' => '记住账号',
    'login.submit' => '登入!',
    'register' => '注册',
    'register.login' => '已经有账户？',
    'register.username' => '用户名',
    'register.email' => '电子邮件地址',
    'register.password' => '密码',
    'register.password-repeat' => '密码再一次',
    'register.captcha' => '我不是机器人：',
    'register.submit' => '註冊!',
    'register.account-created' => '恭喜！ 您的帐号已经建立。 查看您的电子邮件以获取激活消息。 提示：请查看您的垃圾邮件/垃圾邮件文件夹。',
    'register.account-created.title' => '您的％1帐户已创建。',
    'register.account-created.message' => "亲爱的％1，\ r \ n \ r \ \已创建您在％3上的帐户\在您登录之前，必须先激活您的帐户"
      . " 此电子邮件地址有效。 您可以通过单击以下链接激活您的帐户：\ r \ n \％2 \ r \ n \ r \ n \ n \彻底\ r \ n \ n％3团队
",
    'news' => '新闻',
    'news.latest-news' => '最新新闻',
    'news.select-article' => '从列表中选择要阅读的文章',
    'news.read-more' => '阅读更多',
    'news.article.published' => '％1发布在％2上的文章',
    'staff' => '员工',
    'user.last-online' => '最后一次在线看到％1',
    'user.my-page' => '我的页面',
    'user.logout'=>'退出'，
    'user.online'=>'在线'，
    'user.offline'=>'离线'，
    'user.settings'=>'设置'，
    'user.settings.my-preferences'=>'我的偏好'，
    'user.settings.my-password'=>'我的密码'，
    'user.settings.my-email'=>'我的电子邮件地址'，
    'user.settings.change-password'=>'更改密码'，
    'user.settings.change-email'=>'更改电子邮件地址'，
    'user.settings.e-mail'=>'电子邮件地址'，
    'user.settings.change-email.description'=>'想要更改您的电子邮件地址？'，
    'user.settings.my-status'=>'我的状态'，
    'user.settings.my-status.description'=>'你的状态是什么？'，
    'user.settings.online-status'=>'在线状态'，
    'user.settings.online-status.description'=>'谁能看到你在线？'，
    'user.settings.online-status.everybody'=>'每个人'，
    'user.settings.online-status.nobody'=>'没人'，
    'user.settings.friends-follow'=>'朋友关注'，
    'user.settings.friends-follow.description'=>'朋友可以在酒店关注你吗？'，
    'user.settings.friends-follow.yes'=>'是的，没关系'，
    'user.settings.friends-follow.no'=>'不，请不要'，
    'user.settings.change-my-password'=>'更改我的密码'，
    'user.settings.change-my-password.description'=>'你害怕有人知道你的密码吗？在这里改变它。'，
    'user.settings.current-password'=>'当前密码'，
    'user.settings.new-email'=>'您的新电子邮件地址'，
    'user.settings.new-email-repeat'=>'您的新电子邮件地址（重复）'，
    'user.settings.new-password'=>'您的新密码'，
    'user.settings.new-password-repeat'=>'您的新密码（重复）'，
    'user.settings.save'=>'保存'，
    'user.settings.error.email-incorrect'=>'这不是有效的电子邮件地址。'，
    'user.settings.error.password-incorrect'=>'输入的密码不正确。'，
    'user.settings.error.passwords-dont-match'=>'输入的密码不匹配。'，
    'user.settings.error.password-too-short'=>'输入的密码太短。'，
    'user.settings.error.emails-dont-match'=>'输入的电子邮件地址不匹配。'，
    'user.settings.success.preferences-changed'=>'您的偏好已更新！'，
    'user.settings.success.email-changed'=>'您的电子邮件地址已更新！'，
    'user.settings.success.password-changed'=>'您的密码已更新！'，
    'community'=>'社区'，
    'community.staff'=>'工作人员'，
    'community.staff.staff-on-hotel'=>'％1上的员工'，
    'community.richest-members'=>'最富有的成员'，
    'community.popular-rooms'=>'热门客房'，
    'admin'=>'家政'，
    'admin.dashboard'=>'信息中心'，
    'admin.welcome'=>'欢迎，％1'，
    'admin.settings'=>'设置'，
    'admin.settings.cms'=>'CMS设置'，
    'admin.settings.client'=>'客户端设置'，
    'admin.settings.plugin'=>'插件设置'，
    'admin.settings.register'=>'注册设置'，
    'admin.settings.setting.base_url'=>'网站基础网址'，
    'admin.settings.setting.hotel_name'=>'酒店名称'，
    'admin.settings.setting.hotel_slogan'=>'Hotel Slogan'，
    'admin.settings.setting.language'=>'语言'，
    'admin.settings.setting.logo_url'=>'徽标网址'，
    'admin.settings.logo-url-live-preview'=>'实时徽标预览'，
    'admin.settings.setting.password_min_length'=>'最小密码长度'，
    'admin.settings.setting.skin'=>'CMS Skin'，
    'admin.settings.setting.maintainance'=>'维护模式'，
    'admin.settings.setting.avatar_image_url'=>'头像图片网址'，
    'admin.settings.setting.client_css'=>'客户端CSS网址'，
    'admin.settings.setting.client_emu_ip'=>'模拟器IP'，
    'admin.settings.setting.client_emu_port'=>'仿真端口'，
    'admin.settings.setting.client_js'=>'客户端JS网址'，
    'admin.settings.setting.client_mus_ip'=>'模拟器MUS IP'，
    'admin.settings.setting.client_mus_port'=>'模拟器MUS端口'，
    'admin.settings.setting.client_swf_dir'=>'SWF目录网址'，
    'admin.settings.setting.client_swf_express'=>'expressInstall.swf URL'，
    'admin.settings.setting.client_swf_ext_texts'=>'外部Flash文本网址'，
    'admin.settings.setting.client_swf_ext_vars'=>'外部变量网址'，
    'admin.settings.setting.client_swf_habbo'=>'Habbo.swf网址'，
    'admin.settings.setting.register_activity_points'=>'新用户活动点'，
    'admin.settings.setting.register_credits'=>'新用户信用'，
    'admin.settings.setting.register_vip_points'=>'新用户VIP积分'，
    'admin.settings.setting.register_look'=>'新用户看'，
    'admin.settings.setting.register_motto'=>'新用户座右铭'，
    'admin.settings.save'=>'保存设置！'，
    'admin.settings.saved'=>'设置已保存！'，
    'admin.news'=>'新闻'，
    'admin.news.deleted'=>'已删除的文章'，
    'admin.news.success.published'=>'文章成功发布！'，
    'admin.news.success.updated'=>'文章已成功更新！'，
    'admin.news.success.moved-to-trash'=>'文章已成功移至垃圾箱。'，
    'admin.news.success.deleted'=>'文章已永久成功删除。'，
    'admin.news.error.couldnt-create'=>'保存文章时出错了。'，
    'admin.news.edit-article'=>'编辑文章：％1'，
    'admin.news.new-article'=>'写新文章'，
    'admin.news.title'=>'标题'，
    'admin.news.lead'=>'领导'，
    'admin.news.message'=>'完整消息'，
    'admin.news.image'=>'图片'，
    'admin.news.image-live-preview'=>'图片预览'，
    'admin.news.publish'=>'发布！'，
    'admin.news.save'=>'保存编辑！'，
    'admin.users-and-ranking'=>'用户和排名'，
    'admin.users.ban'=>'禁令！'，
    'admin.users.edit'=>'编辑用户'，
    'admin.ranks'=>'排名'，
    'admin.ranks.badge'=>'徽章'，
    'admin.ranks.name'=>'排名'，
    'admin.ranks.edit'=>'编辑排名＃％1：％2'，
    'admin.ranks.visibility'=>'可见性'，
    'admin.ranks.visible'=>'可见'，
    'admin.ranks.invisible'=>'隐形'，
    'admin.ranks.save'=>'保存等级'，
    'admin.ranks.error.couldnt-save'=>'无法保存排名。'，
    'admin.ranks.error.doesnt-exist'=>'无法找到等级。'，
    'admin.ranks.success.updated'=>'排名已成功更新。'，
    'admin.banned-users'=>'禁止用户'，
    'admin.banned-ips'=>'禁止的IP'，
    'admin.plugins'=>'插件'，
    'admin.plugins.enabled-plugins'=>'启用插件（％1）'，
    'admin.plugins.disabled-plugins'=>'已禁用的插件（％1）'，
    'admin.plugins.edit'=>'编辑设置'，
    'admin.plugins.disable'=>'禁用插件'，
    'admin.plugins.enable'=>'启用插件'，
    'admin.plugins.no-enabled'=>'没有启用的插件'，
    'admin.plugins.no-disabled'=>'没有禁用的插件'，
    'admin.plugins.plugin-enabled'=>'插件已启用'，
    'admin.plugins.plugin-disabled'=>'该插件被禁用'，
    'admin.plugins.no-settings'=>'此插件未定义任何设置'，
    'admin.plugins.saved'=>'设置已保存'，
    'admin.plugins.couldnt-save'=>'保存设置时出错'，
    'admin.pages'=>'页面'，
    'admin.pages.edit'=>'编辑页面：％1'，
    'admin.pages.name'=>'页面名称'，
    'admin.pages.no-pages'=>'你还没有创建任何页面。'，
    'admin.pages.access-level'=>'访问级别'，
    'admin.pages.access-level.all'=>'每个人'，
    'admin.pages.access-level.guest'=>'只有客人'，
    'admin.pages.access-level.user'=>'注册用户'，
    'admin.pages.access-level.mod'=>'主持人'，
    'admin.pages.access-level.admin'=>'管理员'，
    'admin.pages.add-column'=>'添加列'，
];