 <?php

$lang = [
    'translation.language' => 'Deutsch',
    'translation.translator' => 'C0R3G4M3R',
    'translation.translator.url' => 'https://forum.ragezone.com/members/1333430713.html',
    'translation.last-updated' => 'August 10th 2015',

    'error.page-not-found' => 'Seite nicht gefunden',
    'error.page-not-found.description' => 'Die gewünschte Seite konnte nicht gefunden werden.',
    'error.no-access' => 'Kein Zugriff',
    'error.no-access.description' => 'Du hast keine rechte (mehr) um diese Seite zu sehen.',
    'error.return-to-home' => 'Zur Startseite zurückkehren.',

    'error.login.login' => 'Es gibt keinen Account mit diesem Nutzernamen oder E-Mail Adresse.',
    'error.login.password' => 'Das eingegebene Passwort ist fehlerhaft.',
    'error.login.banned' => 'Dieser Account wurde gebannt. Grund: %1',
    'error.login.blocked' => 'Der Loginversuch wurde geblockt.',

    'error.register.username.legnth' => 'Dein Nutzername kann aus 3 bis maximal 20 Zeichen bestehen.',
    'error.register.username.not-available' => 'Dieser Nutzername ist nicht verfügbar.',
    'error.register.password.length' => 'Dein Passwort muss mindestens 8 Zeichen lang sein.',
    'error.register.password.dont-match' => 'Die angegebenen Passwörter stimmen nicht überein',
    'error.register.email.not-available' => 'Die angegebene E-Mail Adresse wird bereits verwendet.',
    'error.register.email.format' => 'Die angegebene E-Mail Adresse ist ungültig.',
    'error.register.blocked' => 'This registration attempt was blocked.',

    'general.advertisement' => 'Werbung',
    'general.users-online' => 'Es sind %1 spieler online!',
    'general.welcome' => 'Willkommen im %1',
    'general.register-now' => 'Registriere dich im %1',
    'general.enter-hotel' => 'Enter %1!',
    'general.logged-out' => 'Du hast dich erfolgreich ausgeloggt! Auf wiedersehen.',
    'general.welcome-back' => 'Willkommen zurück, %1',

    'login' => 'Einloggen',
    'login.username-or-email' => 'Nutzername oder E-Mail',
    'login.password' => 'Passwort',
    'login.remember-me' => 'Merken',
    'login.submit' => 'Einloggen!',

    'register' => 'Registrieren',
    'register.login' => 'Already have an account?',
    'register.username' => 'Nutzername',
    'register.email' => 'E-Mail Addresse',
    'register.password' => 'Passwort',
    'register.password-repeat' => 'Passwort (wiederholen)',
    'register.captcha' => 'Ich bin kein Roboter:',
    'register.submit' => 'Registerieren!',
    'register.account-created' => 'Herzlichen Glückwunsch! Dein Account wurde erstellt. Überprüfe deine E-Mail für die Aktivierung. TIPP: Gucke auch in deinen Spam/Junk Ordner.',
    'register.account-created.title' => 'Dein Account im %1 wurde erstellt.',
    'register.account-created.message' => "%1,\r\n\r\nDein Account im %3 wurde erstellt.\r\nBevor du dich einloggen kannst, musst du deinen Account zuerst aktivieren. Dann sind wir uns sicher"
     . ", dass diese E-Mail Adresse gültig ist. Klicke folgenden Link zum Aktivieren:\r\n\%2\r\n\r\nSincerely\r\nThe %3 team",

    'news' => 'News',
    'news.latest-news' => 'Die letzten news',
    'news.select-article' => 'Wähle einen Artikel aus der Liste um ihn zu lesen',
    'news.read-more' => 'Weiter lesen',
    'news.article.published' => 'Der Artikel wurde am %2 von %1 verfasst',

    'staff' => 'Staff',

    'user.last-online' => 'Zuletzt online gewesen am %1',
    'user.my-page' => 'Meine Seite',
    'user.logout' => 'Ausloggen',
    'user.online' => 'Online',
    'user.offline' => 'Offline',

    'user.settings' => 'Einstellungen',
    'user.settings.my-preferences' => 'Meine Einstellungen',
    'user.settings.my-password' => 'Mein Passwort',
    'user.settings.my-email' => 'Meine E-Mail Addresse',
    'user.settings.change-password' => 'Passwort ändern',
    'user.settings.change-email' => 'E-Mail Addresse ändern',
    'user.settings.e-mail' => 'E-Mail Addresse',
    'user.settings.change-email.description' => 'Du möchtest deine E-Mail Adresse ändern?',
    'user.settings.my-status' => 'Mein Status',
    'user.settings.my-status.description' => 'Wie ist dein Status?',
    'user.settings.online-status' => 'Online Status',
    'user.settings.online-status.description' => 'Wer kann sehen, ob du online bist?',
    'user.settings.online-status.everybody' => 'Jeder',
    'user.settings.online-status.nobody' => 'Niemand',
    'user.settings.friends-follow' => 'Freunde folgen',
    'user.settings.friends-follow.description' => 'Können dir deine Freunde im Hotel folgen?',
    'user.settings.friends-follow.yes' => 'Ja, gerne',
    'user.settings.friends-follow.no' => 'Nein, danke',
    'user.settings.change-my-password' => 'Mein Passwort ändern',
    'user.settings.change-my-password.description' => 'Du denkst, dass jemand dein Passwort kennt? Ändere es hier.',
    'user.settings.current-password' => 'Derzeitiges Passwort',
    'user.settings.new-email' => 'Deine neue E-Mail Adresse',
    'user.settings.new-email-repeat' => 'Deine neue E-Mail Adresse (wiederholen)',
    'user.settings.new-password' => 'Dein neues Passwort',
    'user.settings.new-password-repeat' => 'Dein neues Passwort (wiederholen)',
    'user.settings.save' => 'Speichern',
    'user.settings.error.email-incorrect' => 'Die angegebene E-Mail Adresse ist ungültig.',
    'user.settings.error.password-incorrect' => 'Das angegebene Passwort ist fehlerhaft.',
    'user.settings.error.passwords-dont-match' => 'Die angegebenen Passwörter stimmen nicht überein.',
    'user.settings.error.password-too-short' => 'Das angegebene Passwort ist zu kurz.',
    'user.settings.error.emails-dont-match' => 'Die angegebenen E-Mail Adressen stimmen nicht überein.',
    'user.settings.success.preferences-changed' => 'Deine Einstellungen wurden gespeichert!',
    'user.settings.success.email-changed' => 'Deine E-Mail Adresse wurde geändert!',
    'user.settings.success.password-changed' => 'Dein Passwort wurde geändert!',

    'community' => 'Community',
    'community.staff' => 'Staff Mitglieder',
    'community.staff.staff-on-hotel' => 'Staffs im %1',
    'community.richest-members' => 'Reichste Spieler',

    'admin' => 'Housekeeping',
    'admin.dashboard' => 'Dashboard',
    'admin.welcome' => 'Welcome, %1',
    'admin.settings' => 'Einstellungen',

    'admin.settings.cms' => 'CMS Einstellungen',
    'admin.settings.client' => 'Client Einstellungen',
    'admin.settings.plugin' => 'Plugin Einstellungen',
    'admin.settings.register' => 'Registrations Einstellungen',
    'admin.settings.setting.base_url' => 'Standard URL',
    'admin.settings.setting.hotel_name' => 'Hotel Name',
    'admin.settings.setting.hotel_slogan' => 'Hotel Slogan',
    'admin.settings.setting.language' => 'Sprache',
    'admin.settings.setting.logo_url' => 'Logo URL',
    'admin.settings.setting.password_min_length' => 'Mindest Passwort Länge',
    'admin.settings.setting.skin' => 'CMS Skin',
    'admin.settings.setting.maintainance' => 'Wartungsmodus',
    'admin.settings.setting.avatar_image_url' => 'Avatar Image URL',
    'admin.settings.setting.client_css' => 'Client CSS URL',
    'admin.settings.setting.client_emu_ip' => 'Emulator IP',
    'admin.settings.setting.client_emu_port' => 'Emulator Port',
    'admin.settings.setting.client_js' => 'Client JS URL',
    'admin.settings.setting.client_mus_ip' => 'Emulator MUS IP',
    'admin.settings.setting.client_mus_port' => 'Emulator MUS Port',
    'admin.settings.setting.client_swf_dir' => 'SWF Ordner URL',
    'admin.settings.setting.client_swf_express' => 'expressInstall.swf URL',
    'admin.settings.setting.client_swf_ext_texts' => 'External Flash Texts URL',
    'admin.settings.setting.client_swf_ext_vars' => 'External Variables URL',
    'admin.settings.setting.client_swf_habbo' => 'Habbo.swf URL',
    'admin.settings.setting.register_activity_points' => 'Acitivitätspunkte für neue Nutzer',
    'admin.settings.setting.register_credits' => 'Credits für neue Nutzer',
    'admin.settings.setting.register_vip_points' => 'VIP Punkte für neue Nutzer',
    'admin.settings.setting.register_look' => 'Look für neue Nutzer',
    'admin.settings.setting.register_motto' => 'Motto für neue Nutzer',
    'admin.settings.save' => 'Einstellungen speichern!',
    'admin.settings.saved' => 'Die Einstellungen wurden gespeichert!',

    'admin.news' => 'Neuigkeiten',
    'admin.news.success.article-published' => 'Der Artikel wurde erfolgreich veröffentlicht!',
    'admin.news.creation-error' => 'Etwas ist wärend des speicherns schiefgegangen.',
    'admin.news.edit-article' => 'Artikel bearbeiten: %1',
    'admin.news.new-article' => 'Neuen Artikel verfassen',
    'admin.news.title' => 'Titel',
    'admin.news.lead' => 'Lead',
    'admin.news.message' => 'Nachricht',
    'admin.news.image' => 'Bild',
    'admin.news.image-live-preview' => 'Bildvorschau',
    'admin.news.publish' => 'Veröffentlichen!',

    'admin.users' => 'Nutzer',
    'admin.users.ban' => 'Bann!',
    'admin.users.edit' => 'Nutzer bearbeiten',

    'admin.plugins' => 'Plugins',
    'admin.plugins.enabled-plugins' => 'Aktivierte Plugins (%1)',
    'admin.plugins.disabled-plugins' => 'Deaktivierte Plugins (%1)',
    'admin.plugins.edit' => 'Einstellungen bearbeiten',
    'admin.plugins.disable' => 'Plugins deaktivieren',
    'admin.plugins.enable' => 'Plugins aktivieren',
    'admin.plugins.no-enabled' => 'Es ist derzeit kein Plugins aktiviert',
    'admin.plugins.no-disabled' => 'Es ist derzeit kein Plugins deaktiviert',
    'admin.plugins.plugin-enabled' => 'Das Plugin wurde aktiviert',
    'admin.plugins.plugin-disabled' => 'Das Plugin wurde deaktiviert',
    'admin.plugins.no-settings' => 'Dieses Plugin hat keine Einstellungen',
    'admin.plugins.saved' => 'Die Einstellungen wurden gespeichert',
    'admin.plugins.couldnt-save' => 'Etwas ist schiefgegangen wärend des speicherns',

    'admin.pages' => 'Seiten',
    'admin.pages.edit' => 'Seite bearbeiten: %1',
    'admin.pages.name' => 'Seiten Name',
    'admin.pages.access-level' => 'Access level',
    'admin.pages.access-level.all' => 'Jeder',
    'admin.pages.access-level.guest' => 'Nur Gäste',
    'admin.pages.access-level.user' => 'Registrierte Nutzer',
    'admin.pages.access-level.mod' => 'Moderatoren',
    'admin.pages.access-level.admin' => 'Administratoren',
    'admin.pages.add-column' => 'Column hinzufügen',
];
