<?php

$lang = [
    'translation.language' => 'English',
    'translation.translator' => 'Xesau',
    'translation.translator.url' => 'https://uhabbo.xesau.eu',
    'translation.last-updated' => 'August 24th 2015',

    'error.page-not-found' => 'Page not found',
    'error.page-not-found.description' => 'The requested page could not be found.',
    'error.no-access' => 'No access',
    'error.no-access.description' => 'You don\'t have access to this page (anymore).',
    'error.return-to-home' => 'Return to the homepage.',

    'error.login.login' => 'There is no account with this username or e-mail address.',
    'error.login.password' => 'The entered password is incorrect.',
    'error.login.banned' => 'This account has been banned. Reason: %1',
    'error.login.blocked' => 'The login attemt was blocked.',

    'error.register.username.legnth' => 'Your username must at least be 3 characters long and may not be longer than 20.',
    'error.register.username.not-available' => 'This username is not available anymore.',
    'error.register.password.length' => 'Your password must be at least 8 characters long.',
    'error.register.password.dont-match' => 'The entered passwords don\'t match',
    'error.register.email.not-available' => 'There already is an account with this e-mail address.',
    'error.register.email.format' => 'This e-mail address is not valid.',
    'error.register.blocked' => 'This registration attempt was blocked.',

    'general.advertisement' => 'Advertisement',
    'general.users-online' => 'There are %1 players online!',
    'general.welcome' => 'Welcome to %1',
    'general.register-now' => 'Register now on %1',
    'general.enter-hotel' => 'Enter %1!',
    'general.logged-out' => 'Your are logged out! Goodbye.',
    'general.welcome-back' => 'Welcome back, %1',

    'login' => 'Login',
    'login.username-or-email' => 'Username or e-mail',
    'login.password' => 'Password',
    'login.remember-me' => 'Remember me',
    'login.submit' => 'Log in!',

    'register' => 'Register',
    'register.login' => 'Already having an account?',
    'register.username' => 'Username',
    'register.email' => 'E-mail address',
    'register.password' => 'Password',
    'register.password-repeat' => 'Password (repeat)',
    'register.captcha' => 'I am not a robot:',
    'register.submit' => 'Register!',
    'register.account-created' => 'Congratulations! Your account has been created. Check your e-mail for the activation message. TIP: Take a look at your spam/junk folder too.',
    'register.account-created.title' => 'Your account on %1 has been created.',
    'register.account-created.message' => "Dear %1,\r\n\r\nYour account on %3 has been created.\r\nBefore you can log in, your account must be activated first. So we are sure"
      . " this e-mail address is valid. You can activate your account by clicking the following link:\r\n\%2\r\n\r\nSincerely\r\nThe %3 team",

    'news' => 'News',
    'news.latest-news' => 'The latest news',
    'news.select-article' => 'Select an article from the list to read',
    'news.read-more' => 'Read more',
    'news.article.published' => 'Article published on %2 by %1',

    'staff' => 'Staff',

    'user.last-online' => 'Last seen online on %1',
    'user.my-page' => 'My page',
    'user.logout' => 'Log out',
    'user.online' => 'Online',
    'user.offline' => 'Offline',

    'user.settings' => 'Settings',
    'user.settings.my-preferences' => 'My preferences',
    'user.settings.my-password' => 'My password',
    'user.settings.my-email' => 'My e-mail address',
    'user.settings.change-password' => 'Change password',
    'user.settings.change-email' => 'Change e-mail address',
    'user.settings.e-mail' => 'E-mail address',
    'user.settings.change-email.description' => 'Want to change your e-mail address?',
    'user.settings.my-status' => 'My status',
    'user.settings.my-status.description' => 'What is your status?',
    'user.settings.online-status' => 'Online status',
    'user.settings.online-status.description' => 'Who can see you are online?',
    'user.settings.online-status.everybody' => 'Everybody',
    'user.settings.online-status.nobody' => 'Nobody',
    'user.settings.friends-follow' => 'Friends follow',
    'user.settings.friends-follow.description' => 'Can friends follow you in the hotel?',
    'user.settings.friends-follow.yes' => 'Yes, that\'s okay',
    'user.settings.friends-follow.no' => 'No, please not',
    'user.settings.change-my-password' => 'Change my password',
    'user.settings.change-my-password.description' => 'Are you afraid someone knows your password? Change it here.',
    'user.settings.current-password' => 'Current password',
    'user.settings.new-email' => 'Your new e-mail address',
    'user.settings.new-email-repeat' => 'Your new e-mail address (repeat)',
    'user.settings.new-password' => 'Your new password',
    'user.settings.new-password-repeat' => 'Your new password (repeat)',
    'user.settings.save' => 'Save',
    'user.settings.error.email-incorrect' => 'This is not a valid e-mail address.',
    'user.settings.error.password-incorrect' => 'The entered password is incorrect.',
    'user.settings.error.passwords-dont-match' => 'The entered passwords don\'t match.',
    'user.settings.error.password-too-short' => 'The entered password is too short.',
    'user.settings.error.emails-dont-match' => 'The entered e-mail addresses don\'t match.',
    'user.settings.success.preferences-changed' => 'Your preferences were updated!',
    'user.settings.success.email-changed' => 'Your e-mail address was updated!',
    'user.settings.success.password-changed' => 'Your password was updated!',

    'community' => 'Community',
    'community.staff' => 'Staff members',
    'community.staff.staff-on-hotel' => 'Staff on %1',
    'community.richest-members' => 'Richest members',

    'admin' => 'Housekeeping',
    'admin.dashboard' => 'Dashboard',
    'admin.welcome' => 'Welcome, %1',
    'admin.settings' => 'Settings',

    'admin.settings.cms' => 'CMS Settings',
    'admin.settings.client' => 'Client Settings',
    'admin.settings.plugin' => 'Plugin Settings',
    'admin.settings.register' => 'Registration Settings',
    'admin.settings.setting.base_url' => 'Site Base URL',
    'admin.settings.setting.hotel_name' => 'Hotel Name',
    'admin.settings.setting.hotel_slogan' => 'Hotel Slogan',
    'admin.settings.setting.language' => 'Language',
    'admin.settings.setting.logo_url' => 'Logo URL',
    'admin.settings.setting.password_min_length' => 'Minimum password length',
    'admin.settings.setting.skin' => 'CMS Skin',
    'admin.settings.setting.maintainance' => 'Maintainance mode',
    'admin.settings.setting.avatar_image_url' => 'Avatar Image URL',
    'admin.settings.setting.client_css' => 'Client CSS URL',
    'admin.settings.setting.client_emu_ip' => 'Emulator IP',
    'admin.settings.setting.client_emu_port' => 'Emulator Port',
    'admin.settings.setting.client_js' => 'Client JS URL',
    'admin.settings.setting.client_mus_ip' => 'Emulator MUS IP',
    'admin.settings.setting.client_mus_port' => 'Emulator MUS Port',
    'admin.settings.setting.client_swf_dir' => 'SWF directory URL',
    'admin.settings.setting.client_swf_express' => 'expressInstall.swf URL',
    'admin.settings.setting.client_swf_ext_texts' => 'External Flash Texts URL',
    'admin.settings.setting.client_swf_ext_vars' => 'External Variables URL',
    'admin.settings.setting.client_swf_habbo' => 'Habbo.swf URL',
    'admin.settings.setting.register_activity_points' => 'New User acitivity points',
    'admin.settings.setting.register_credits' => 'New User credits',
    'admin.settings.setting.register_vip_points' => 'New User VIP points',
    'admin.settings.setting.register_look' => 'New User look',
    'admin.settings.setting.register_motto' => 'New User motto',
    'admin.settings.save' => 'Save settings!',
    'admin.settings.saved' => 'The settings are saved!',

    'admin.news' => 'News',
    'admin.news.success.article-published' => 'Article successfully published!',
    'admin.news.creation-error' => 'Something went wrong while saving the article.',
    'admin.news.edit-article' => 'Edit article: %1',
    'admin.news.new-article' => 'Write new article',
    'admin.news.title' => 'Title',
    'admin.news.lead' => 'Lead',
    'admin.news.message' => 'Full message',
    'admin.news.image' => 'Image',
    'admin.news.image-live-preview' => 'Image preview',
    'admin.news.publish' => 'Publish!',

    'admin.users' => 'Users',
    'admin.users.ban' => 'Ban!',
    'admin.users.edit' => 'Edit user',

    'admin.plugins' => 'Plugins',
    'admin.plugins.enabled-plugins' => 'Enabled plugins (%1)',
    'admin.plugins.disabled-plugins' => 'Disabled plugins (%1)',
    'admin.plugins.edit' => 'Edit settings',
    'admin.plugins.disable' => 'Disable plugin',
    'admin.plugins.enable' => 'Enable plugin',
    'admin.plugins.no-enabled' => 'There are no enabled plugins',
    'admin.plugins.no-disabled' => 'There are no disabled plugins',
    'admin.plugins.plugin-enabled' => 'The plugin was enabled',
    'admin.plugins.plugin-disabled' => 'The plugin was disabled',
    'admin.plugins.no-settings' => 'This plugin does not define any settings',
    'admin.plugins.saved' => 'The settings are saved',
    'admin.plugins.couldnt-save' => 'There was an error while saving the settings',

    'admin.pages' => 'Pages',
    'admin.pages.edit' => 'Edit page: %1',
    'admin.pages.name' => 'Page name',
    'admin.pages.no-pages' => 'You have not yet created any pages.',
    'admin.pages.access-level' => 'Access level',
    'admin.pages.access-level.all' => 'Everyone',
    'admin.pages.access-level.guest' => 'Only guests',
    'admin.pages.access-level.user' => 'Registered users',
    'admin.pages.access-level.mod' => 'Moderators',
    'admin.pages.access-level.admin' => 'Administrators',
    'admin.pages.add-column' => 'Add column',
];
