<?php

$lang = [
    'translation.language' => 'Español',
    'translation.translator' => 'Parnstermia',
    'translation.translator.url' => 'https://github.com/Parnstermia',
    'translation.last-updated' => '8th May 2016',

    'error.page-not-found' => 'Página no encontrada.',
    'error.page-not-found.description' => 'La página solicitada no está disponible.',
    'error.no-access' => 'Acceso restringido.',
    'error.no-access.description' => 'No puedes acceder a esta página.',
    'error.return-to-home' => 'Volver a la página principal.',

    'error.login.login' => 'No hay ninguna cuenta con este usuario o correo.',
    'error.login.password' => 'La contraseña introducida es incorrecta.',
    'error.login.banned' => 'Esta cuenta ha sido baneada. Motivo: %1',
    'error.login.blocked' => 'La cuenta ha sido bloqueada.',

    'error.register.username.legnth' => 'Tu usuario debe tener de  3 a 20 caracteres.',
    'error.register.username.not-available' => 'El nombre de usuario no está disponible.',
    'error.register.password.length' => 'La contraseña debe tener una longitud mínima de 8 cifras/caracteres.',
    'error.register.password.dont-match' => 'Las contraseñas introducidas no coinciden.',
    'error.register.email.not-available' => 'Ya existe una cuenta con ese correo electrónico.',
    'error.register.email.format' => 'El correo no es valido.',
    'error.register.blocked' => 'El intento de registro ha sido bloqueado.',

    'general.advertisement' => 'Anuncio',
    'general.users-online' => '¡Hay %1 jugadores en linea!',
    'general.welcome' => 'Bienvenido a  %1',
    'general.register-now' => 'Registrate ahora en %1',
    'general.enter-hotel' => '¡Entrar a  %1!',
    'general.logged-out' => 'Te has desconectado. Hasta luego!.',
    'general.welcome-back' => 'Bienvenido de nuevo, %1',

    'login' => 'Identificarse',
    'login.username-or-email' => 'Usuario o correo',
    'login.password' => 'Contraseña',
    'login.remember-me' => 'Recuerdame',
    'login.submit' => '¡Identificame!',

    'register' => 'Registro',
    'register.login' => '¿Tienes ya una cuenta?',
    'register.username' => 'Usuario',
    'register.email' => 'Correo electrónico',
    'register.password' => 'Contraseña',
    'register.password-repeat' => 'Repite la contraseña',
    'register.captcha' => 'No soy un robot:',
    'register.submit' => '¡Registrame!',
    'register.account-created' => '¡Enhorabuena! Tu cuenta ha sido creada, por favor comprueba en tu correo el mensaje de activación. Comprueba también la carpeta de spam.',
    'register.account-created.title' => 'Tu cuenta en  %1 ha sido creada.',
    'register.account-created.message' => "Querido %1,\r\n\r\nTu cuenta de  %3 se ha creado.\r\nAntes de identificarte, tu cuenta debe ser activada. Por lo que"
      . " ¿estas seguro de que el correo es valido?. Puedes activar tu cuenta haciendo click en el siguiente enlace:\r\n\%2\r\n\r\nAtentamente\r\nEl equipo de %3 ",

    'news' => 'Noticias',
    'news.latest-news' => 'Ultimas noticias',
    'news.select-article' => 'Selecciona un articulo de la lista para leerlo',
    'news.read-more' => 'Leer más',
    'news.article.published' => 'Artículo publicado el %2 por %1',

    'staff' => 'Staff',

    'user.last-online' => 'Última vez en linea %1',
    'user.my-page' => 'Perfil',
    'user.logout' => 'Desconectarse',
    'user.online' => 'En linea',
    'user.offline' => 'Desconectado',

    'user.settings' => 'Configuración',
    'user.settings.my-preferences' => 'Preferencias',
    'user.settings.my-password' => 'Contraseña',
    'user.settings.my-email' => 'Correo electrónico',
    'user.settings.change-password' => 'Cambiar contraseña',
    'user.settings.change-email' => 'Cambiar correo elctrónico',
    'user.settings.e-mail' => 'Correo electrónico',
    'user.settings.change-email.description' => '¿Quieres cambiar tu correo?',
    'user.settings.my-status' => 'Estado',
    'user.settings.my-status.description' => '¿Cuál es tu estado?',
    'user.settings.online-status' => 'estado en línea',
    'user.settings.online-status.description' => '¿Quien puede ver que estás conectado?',
    'user.settings.online-status.everybody' => 'Todo el mundo',
    'user.settings.online-status.nobody' => 'Nadie',
    'user.settings.friends-follow' => 'Amigos',
    'user.settings.friends-follow.description' => '¿Tus amigos te pueden seguir en el hotel?',
    'user.settings.friends-follow.yes' => 'Sí, está bien',
    'user.settings.friends-follow.no' => 'No, por favor',
    'user.settings.change-my-password' => 'Cambiar contraseña',
    'user.settings.change-my-password.description' => '¿Crees que alguien conoce tu contraseña? Cambiala aquí.',
    'user.settings.current-password' => 'Contraseña actual',
    'user.settings.new-email' => 'Nuevo correo electrónico',
    'user.settings.new-email-repeat' => 'Repite tu nuevo correo electrónico',
    'user.settings.new-password' => 'Tu nueva contraseña',
    'user.settings.new-password-repeat' => 'Repite tu nueva contraseña',
    'user.settings.save' => 'Guardar',
    'user.settings.error.email-incorrect' => 'El correo introducido no es válido.',
    'user.settings.error.password-incorrect' => 'La contraseña introducida es incorrecta.',
    'user.settings.error.passwords-dont-match' => 'Las contraseñas introducidas son diferentes.',
    'user.settings.error.password-too-short' => 'La contraseña es demasiado corta.',
    'user.settings.error.emails-dont-match' => 'Los correos introducidos no coinciden.',
    'user.settings.success.preferences-changed' => '¡Tus preferencias han sido actualizadas!',
    'user.settings.success.email-changed' => '¡Tu correo electrónico ha sido actualizado!',
    'user.settings.success.password-changed' => '¡Tu contraseña ha sido actualizada!',

    'community' => 'Comunidad',
    'community.staff' => 'miembro del Staff',
    'community.staff.staff-on-hotel' => 'Staff en %1',
    'community.richest-members' => 'Miembros más ricos',

    'admin' => 'Ama de llaves',
    'admin.dashboard' => 'Panel de control',
    'admin.welcome' => 'Bienvenido, %1',
    'admin.settings' => 'Configuración',

    'admin.settings.cms' => 'Configuración CMS',
    'admin.settings.client' => 'Configuración del cliente',
    'admin.settings.plugin' => 'Configuración de Plugins',
    'admin.settings.register' => 'Configuración de registro',
    'admin.settings.setting.base_url' => 'Enlace base',
    'admin.settings.setting.hotel_name' => 'Nombre del hotel',
    'admin.settings.setting.hotel_slogan' => 'Hotel Slogan',
    'admin.settings.setting.language' => 'Lenguaje',
    'admin.settings.setting.logo_url' => 'Logo URL',
    'admin.settings.setting.password_min_length' => 'Minima longitud de contraseña',
    'admin.settings.setting.skin' => 'Tema CMS',
    'admin.settings.setting.maintainance' => 'Modo mantenimiento',
    'admin.settings.setting.avatar_image_url' => 'Avatar imagen URL',
    'admin.settings.setting.client_css' => 'CLiente URL CSS',
    'admin.settings.setting.client_emu_ip' => 'Emulador IP',
    'admin.settings.setting.client_emu_port' => 'Emulador Puerto',
    'admin.settings.setting.client_js' => 'Cliente JS URL',
    'admin.settings.setting.client_mus_ip' => 'Emulador MUS IP',
    'admin.settings.setting.client_mus_port' => 'Emulador MUS Port',
    'admin.settings.setting.client_swf_dir' => 'Directorio SWF URL',
    'admin.settings.setting.client_swf_express' => 'instalacionExpress.swf URL',
    'admin.settings.setting.client_swf_ext_texts' => 'Textos flash externos URL',
    'admin.settings.setting.client_swf_ext_vars' => 'Variables externas URL',
    'admin.settings.setting.client_swf_habbo' => 'Habbo.swf URL',
    'admin.settings.setting.register_activity_points' => 'Nuevos puntos de actividad usuario',
    'admin.settings.setting.register_credits' => 'Nuevos créditos de usuario',
    'admin.settings.setting.register_vip_points' => 'Nuevos puntos VIP usuario',
    'admin.settings.setting.register_look' => 'Nueva apariencia de usuario',
    'admin.settings.setting.register_motto' => 'Nueva consigna de usuario',
    'admin.settings.save' => '¡Guardar configuración',
    'admin.settings.saved' => '¡La configuración se ha guardado!',

    'admin.news' => 'Noticias',
    'admin.news.success.article-published' => '¡Artículo posteado correctamente!',
    'admin.news.creation-error' => 'Algo ha ido mal al publicar el artículo.',
    'admin.news.edit-article' => 'Editar el artículo: %1',
    'admin.news.new-article' => 'Escribir nuevo artículo',
    'admin.news.title' => 'Título',
    'admin.news.lead' => 'Cabecera',
    'admin.news.message' => 'Mensaje completo',
    'admin.news.image' => 'Imagen',
    'admin.news.image-live-preview' => 'Previsualización de imagen',
    'admin.news.publish' => '¡Publicar!',

    'admin.users' => 'Usuarios',
    'admin.users.ban' => '¡Banear!',
    'admin.users.edit' => 'Editar usuario',

    'admin.plugins' => 'Plugins',
    'admin.plugins.enabled-plugins' => 'Plugins activados (%1)',
    'admin.plugins.disabled-plugins' => 'Plugins desactivados (%1)',
    'admin.plugins.edit' => 'Editar configuración',
    'admin.plugins.disable' => 'Disabilitar plugin',
    'admin.plugins.enable' => 'Habilitar plugin',
    'admin.plugins.no-enabled' => 'No hay plugins activados',
    'admin.plugins.no-disabled' => 'No hay plugins desactivados',
    'admin.plugins.plugin-enabled' => 'El plugin se ha activado',
    'admin.plugins.plugin-disabled' => 'El plugin se ha desactivado',
    'admin.plugins.no-settings' => 'Este plugin no define ninguna configuración',
    'admin.plugins.saved' => 'La configuración se ha guardado',
    'admin.plugins.couldnt-save' => 'Ha ocurrido un error al guardar la nueva configuración',

    'admin.pages' => 'Páginas',
    'admin.pages.edit' => 'Editar página: %1',
    'admin.pages.name' => 'Nombre de página',
    'admin.pages.access-level' => 'Nivel de acceso',
    'admin.pages.access-level.all' => 'Cualquiera',
    'admin.pages.access-level.guest' => 'Solo invitados',
    'admin.pages.access-level.user' => 'Usuarios registrados',
    'admin.pages.access-level.mod' => 'Moderadores',
    'admin.pages.access-level.admin' => 'Administradores',
    'admin.pages.add-column' => 'Añadir columna',
];
