<?php

$lang = [
    'translation.language' => 'Suomi',
    'translation.translator' => 'Infient',
    'translation.translator.url' => 'http://infient.cf',
    'translation.last-updated' => 'October 21th 2015',

    'error.page-not-found' => 'Sivua ei löytynyt',
    'error.page-not-found.description' => 'Hakemaasi sivua ei löytynyt.',
    'error.no-access' => 'Ei oikeuksia',
    'error.no-access.description' => 'Sinulla ei ole oikeuksia avata tätä sivua (enään).',
    'error.return-to-home' => 'Palaa etusivulle.',

    'error.login.login' => 'Syöttämäsi käyttäjänimeä tai sähköpostiosoitetta ei löytynyt.',
    'error.login.password' => 'Syöttämäsi salasana ei täsmää käyttäjän kanssa.',
    'error.login.banned' => 'Tälle käyttäjälle on annettu porttikielto. Syy: %1',
    'error.login.blocked' => 'Kirjautumisyritys estettiin.',

    'error.register.username.legnth' => 'Käyttäjänimesi pitää olla vähintään 3 merkkiä ja maksimissaan 20 merkkiä pitkä.',
    'error.register.username.not-available' => 'Käyttäjänimi on jo käytössä.',
    'error.register.password.length' => 'Salasana pitää olla vähintään 8 merkkiä pitkä.',
    'error.register.password.dont-match' => 'Salasanat eivät täsmää.',
    'error.register.email.not-available' => 'Sähköpostiosoite on jo käytössä.',
    'error.register.email.format' => 'Sähköpostiosoite ei kelpaa.',
    'error.register.blocked' => 'Rekisteröitymisyritys estettiin.',

    'general.advertisement' => 'Mainos',
    'general.users-online' => 'Täällä on %1 käyttäjää paikalla!',
    'general.welcome' => 'Tervetuloa %1n',
    'general.register-now' => 'Rekisteröidy nyt %1n',
    'general.enter-hotel' => 'Osallistu %1!',
    'general.logged-out' => 'Olet kirjautunut ulos.',
    'general.welcome-back' => 'Tervetuloa takaisin, %1',

    'login' => 'Kirjaudu',
    'login.username-or-email' => 'Käyttäjänimi tai sähköposti',
    'login.password' => 'Salasana',
    'login.remember-me' => 'Muista minut',
    'login.submit' => 'Kirjaudu sisään!',

    'register' => 'Rekisteröidy',
    'register.login' => 'Oletko jo rekisteröitynyt?',
    'register.username' => 'Käyttäjänimi',
    'register.email' => 'Sähköpostiosoite',
    'register.password' => 'Salasana',
    'register.password-repeat' => 'Salasana uudelleen',
    'register.captcha' => 'En ole robotti:',
    'register.submit' => 'Rekisteröidy!',
    'register.account-created' => 'Tilisi on luotu. Olemme lähettäneet vahvistusviestin sähköpostiisi. VINKKI: Katso myös roskaposti.',
    'register.account-created.title' => 'Hahmosi %1ssa on luotu.',
    'register.account-created.message' => "Hyvä %1,\r\n\r\nHahmosi %3 on luotu.\r\nEnnen kuin voit kirjautua sinun pitää vahvistaa sähköpostisi, jotta voimme olla varmoja"
      . ", että tämä sähköpostiosoite on pätevä. Voit aktivoida hahmosi painamalla alla olevaa linkkiä:\r\n\%2\r\n\r\nTerveisin\r\%3-tiimi",

    'news' => 'Uutiset',
    'news.latest-news' => 'Viimeisimmät uutiset',
    'news.select-article' => 'Valitse artikkeli listasta lukeaksi sen',
    'news.read-more' => 'Lue lisää',
    'news.article.published' => 'Artikkeli julkaistu %2, julkaisija %1',

    'staff' => 'Henkilökunta',

    'user.last-online' => 'Viimeksi paikalla %1',
    'user.my-page' => 'Minä',
    'user.logout' => 'Kirjaudu ulos',
    'user.online' => 'Paikalla',
    'user.offline' => 'Pois paikalta',

    'user.settings' => 'Asetukset',
    'user.settings.my-preferences' => 'Minun asetukseni',
    'user.settings.my-password' => 'Minun salasanani',
    'user.settings.my-email' => 'Minun sähköpostini',
    'user.settings.change-password' => 'Vaihda salasana',
    'user.settings.change-email' => 'Vaihda sähköpostiosoite',
    'user.settings.e-mail' => 'Sähköpostiosoite',
    'user.settings.change-email.description' => 'Haluatko vaihtaa sähköpostiosoitteen?',
    'user.settings.my-status' => 'Tila',
    'user.settings.my-status.description' => 'Mikä on tilasi?',
    'user.settings.online-status' => 'Online-tila',
    'user.settings.online-status.description' => 'Ketkä voi nähdä, että olet paikalla?',
    'user.settings.online-status.everybody' => 'Kaikki',
    'user.settings.online-status.nobody' => 'Ei kukaan',
    'user.settings.friends-follow' => 'Seuraaminen',
    'user.settings.friends-follow.description' => 'Voiko kaverit seurata sinua hotellissa?',
    'user.settings.friends-follow.yes' => 'Kyllä',
    'user.settings.friends-follow.no' => 'Ei kiitos',
    'user.settings.change-my-password' => 'Vaihda salasana',
    'user.settings.change-my-password.description' => 'Jos epäilet, että joku tietää salasanasi vaihda se täällä.',
    'user.settings.current-password' => 'Nykyinen salasana',
    'user.settings.new-email' => 'Uusi sähköpostiosoite',
    'user.settings.new-email-repeat' => 'Uusi sähköpostiosoite uudelleen',
    'user.settings.new-password' => 'Uusi salasanasi',
    'user.settings.new-password-repeat' => 'Uusi salasanasi uudelleen',
    'user.settings.save' => 'Tallenna',
    'user.settings.error.email-incorrect' => 'Sähköpostiosoite ei kelvannut.',
    'user.settings.error.password-incorrect' => 'Vanha salasana ei ollut oikein.',
    'user.settings.error.passwords-dont-match' => 'Syöttämäsi salasanat eivät täsmänneet.',
    'user.settings.error.password-too-short' => 'Syöttämäsi salasana on liian lyhyt.',
    'user.settings.error.emails-dont-match' => 'Syöttämäsi sähköpostiosoitteet eivät täsmänneet.',
    'user.settings.success.preferences-changed' => 'Asetuksesi on päivitetty!',
    'user.settings.success.email-changed' => 'Sähköpostiosoitteesi on päivitetty!',
    'user.settings.success.password-changed' => 'Salasanasi on päivitetty!',

    'community' => 'Yhteisö',
    'community.staff' => 'Hotellin henkilökunta',
    'community.staff.staff-on-hotel' => 'Henkilökunta %1',
    'community.richest-members' => 'Rikkaimmat hahmot',
    'community.popular-rooms' => 'Suositut huoneet',

    'admin' => 'Hallintapaneeli',
    'admin.dashboard' => 'Aloituspaneeli',
    'admin.welcome' => 'Tervetuloa, %1',
    'admin.settings' => 'Asetukset',

    'admin.settings.cms' => 'CMS Asetukset',
    'admin.settings.client' => 'Client Asetukset',
    'admin.settings.plugin' => 'Lisäosa-asetukset',
    'admin.settings.register' => 'Rekisteröitymis-asetukset',
    'admin.settings.setting.base_url' => 'Sivun URL',
    'admin.settings.setting.hotel_name' => 'Hotellin nimi',
    'admin.settings.setting.hotel_slogan' => 'Hotellin slogan',
    'admin.settings.setting.language' => 'Kieli',
    'admin.settings.setting.logo_url' => 'Logon URL',
    'admin.settings.logo-url-live-preview' => 'Logon Esikatselu',
    'admin.settings.setting.password_min_length' => 'Salasanan minimipituus',
    'admin.settings.setting.skin' => 'CMS Skin',
    'admin.settings.setting.maintainance' => 'Huoltokatko-tila',
    'admin.settings.setting.avatar_image_url' => 'Avatar-kuva URL',
    'admin.settings.setting.client_css' => 'Client CSS URL',
    'admin.settings.setting.client_emu_ip' => 'Emulaattorin IP',
    'admin.settings.setting.client_emu_port' => 'Emulaattorin Portti',
    'admin.settings.setting.client_js' => 'Client JS URL',
    'admin.settings.setting.client_mus_ip' => 'Emulaattorin MUS IP',
    'admin.settings.setting.client_mus_port' => 'Emulattorin MUS Portti',
    'admin.settings.setting.client_swf_dir' => 'SWF-kansion URL',
    'admin.settings.setting.client_swf_express' => 'expressInstall.swf URL',
    'admin.settings.setting.client_swf_ext_texts' => 'External Flash Texts URL',
    'admin.settings.setting.client_swf_ext_vars' => 'External Variables URL',
    'admin.settings.setting.client_swf_habbo' => 'Habbo.swf URL',
    'admin.settings.setting.register_activity_points' => 'Uuden käyttäjän pikselimäärä',
    'admin.settings.setting.register_credits' => 'Uuden käyttäjän kolikkomäärä',
    'admin.settings.setting.register_vip_points' => 'Uuden käyttäjän pointsimäärä',
    'admin.settings.setting.register_look' => 'Uuden käyttäjän asu',
    'admin.settings.setting.register_motto' => 'Uuden käyttäjän motto',
    'admin.settings.save' => 'Tallenna asetukset!',
    'admin.settings.saved' => 'Asetukset on tallennettu onnistuneesti!',

    'admin.news' => 'Uutiset',
    'admin.news.deleted' => 'Poistetut artikkelit',
    'admin.news.success.published' => 'Artikkeli julkaistu onnistuneesti!',
    'admin.news.success.updated' => 'Artikkeli päivitetty onnistuneesti!',
    'admin.news.success.moved-to-trash' => 'Artikkeli siirretty roskakoriin.',
    'admin.news.success.deleted' => 'Artikkeli poistettu kokonaan.',
    'admin.news.error.couldnt-create' => 'Jokin meni pieleen, kun luotiin uutta artikkelia.',
    'admin.news.edit-article' => 'Muokkaa artikkelia: %1',
    'admin.news.new-article' => 'Kirjoita uusi artikkeli',
    'admin.news.title' => 'Otsikko',
    'admin.news.lead' => 'Lyhyt kuvaus',
    'admin.news.message' => 'Artikkelin sisältö',
    'admin.news.image' => 'Kuva',
    'admin.news.image-live-preview' => 'Kuvan esikatselu',
    'admin.news.publish' => 'Julkaise!',
    'admin.news.save' => 'Tallenna muutokset!',

    'admin.users-and-ranks' => 'Käyttäjät ja tasot',
    'admin.users.ban' => 'Bannaa!',
    'admin.users.edit' => 'Muokkaa käyttäjää',

    'admin.ranks' => 'Tasot',
    'admin.ranks.badge' => 'Merkki',
    'admin.ranks.name' => 'Tason nimi',
    'admin.ranks.edit' => 'Muokkaa tasoa #%1: %2',
    'admin.ranks.visibility' => 'Näkyvyys',
    'admin.ranks.visible' => 'Näkyvä',
    'admin.ranks.invisible' => 'Ei näy',
    'admin.ranks.save' => 'Tallenna taso',
    'admin.ranks.error.couldnt-save' => 'Ei voitu tallentaa tasoa',
    'admin.ranks.error.doesnt-exist' => 'Tasoa ei löytynyt.',
    'admin.ranks.success.updated' => 'Taso päivitetty onnistuneesti.',
    'admin.banned-users' => 'Bannatut käyttäjät',
    'admin.banned-ips' => 'Bannatut IPt',

    'admin.plugins' => 'Lisäosat',
    'admin.plugins.enabled-plugins' => 'Käytössä olevat lisäosat (%1)',
    'admin.plugins.disabled-plugins' => 'Pois käytöstä olevat lisäosat (%1)',
    'admin.plugins.edit' => 'Muokkaa asetuksia',
    'admin.plugins.disable' => 'Poista lisäosa käytöstä',
    'admin.plugins.enable' => 'Laita lisäosa käyttöön',
    'admin.plugins.no-enabled' => 'Ei ole käytössä olevia lisäosia',
    'admin.plugins.no-disabled' => 'Ei ole pois käytöstä olevia lisäosia',
    'admin.plugins.plugin-enabled' => 'Lisäosa laitettiin käyttöön',
    'admin.plugins.plugin-disabled' => 'Lisäosa otettiin pois käytöstä',
    'admin.plugins.no-settings' => 'Lisäosalla ei ole asetuksia',
    'admin.plugins.saved' => 'Asetukset tallennettu',
    'admin.plugins.couldnt-save' => 'Tapahtui virhe tallentaessa lisäosan asetuksia',

    'admin.pages' => 'Sivut',
    'admin.pages.edit' => 'Muokkaa sivua: %1',
    'admin.pages.name' => 'Sivun nimi',
    'admin.pages.no-pages' => 'Et ole luonut yhtään sivua.',
    'admin.pages.access-level' => 'Minimitaso',
    'admin.pages.access-level.all' => 'Kaikki',
    'admin.pages.access-level.guest' => 'Vain vierailijat',
    'admin.pages.access-level.user' => 'Rekisteröityneet käyttäjät',
    'admin.pages.access-level.mod' => 'Valvojat',
    'admin.pages.access-level.admin' => 'Ylläpitäjät',
    'admin.pages.add-column' => 'Lisää sarake',
];
