<?php

$lang = [
    'translation.language' => 'Français',
    'translation.translator' => 'Xesau',
    'translation.translator.url' => 'https://uhabbo.xesau.eu',
    'translation.last-updated' => 'August 3th 2015',

    'error.page-not-found' => 'Page ne pourrait pas trouvé',
    'error.page-not-found.description' => 'La page demandé ne pourrait pas trouvé.',
    'error.no-access' => 'Pas d\'access',
    'error.no-access.description' => 'Tu n\'a pas d\'access a cette page.',
    'error.return-to-home' => 'Reviens à la page d\'accueil.',

    'error.login.login' => 'Il n\'y a pas d\'account avec cette nom ou cette adresse de courrier électronique.',
    'error.login.password' => 'Le mot de passe inscrit est inexact.',
    'error.login.banned' => 'Cette account est exilé. Raison: %1',
    'error.login.blocked' => 'L\'attempt d\'identification était barré.',

    'error.register.username.legnth' => 'Ta nom doit consister de 3 caractères au moins et ne peut être pas plus long de 20.',
    'error.register.username.not-available' => 'Cette nom n\'est pas disponible encore.',
    'error.register.password.length' => 'Ton mot de passe doit être 8 caractères au moins.',
    'error.register.password.dont-match' => 'Les mots de passe inscrit n\'apparient pas.',
    'error.register.email.not-available' => 'Il y a une account avec cette adresse de courrier électronique.',
    'error.register.email.format' => 'Cette adresse de courrier électronique n\'est pas valable.',

    'general.advertisement' => 'Publicité',
    'general.users-online' => 'Il y a %1 joueurs en-ligne!',
    'general.welcome' => 'Bienvenue à %1',
    'general.register-now' => 'S\'enregistre maintenant à %1',
    'general.enter-hotel' => 'Entre %1!',
    'general.logged-out' => 'Tu a fermé ta session! Au revoir.',
    'general.welcome-back' => 'Bienvenue, %1',

    'login' => 'Identifier',
    'login.username-or-email' => 'Nom ou courriel',
    'login.password' => 'Mot de passe',
    'login.remember-me' => 'Me rappele',
    'login.submit' => 'Identifier!',

    'register' => 'Register',
    'register.login' => 'Already have an account?',
    'register.username' => 'Username',
    'register.email' => 'E-mail address',
    'register.password' => 'Password',
    'register.password-repeat' => 'Password (repeat)',
    'register.captcha' => 'I am not a robot:',
    'register.submit' => 'Register!',
    'register.account-created' => 'Congratulations! Your account has been created. Check your e-mail for the activation message. TIP: Take a look at your spam/junk folder too.',
    'register.account-created.title' => 'Your account on %1 has been created.',
    'register.account-created.message' => "Dear %1,\r\n\r\nYour account on %3 has been created.\r\nBefore you can log in, your account must be activated first. So we are sure"
      . " this e-mail address is valid. You can activate your account by clicking the following link:\r\n\%2\r\n\r\nSincerely\r\nThe %3 team",

    'news' => 'News',
    'news.latest-news' => 'The latest news',
    'news.select-article' => 'Select an article from the list to read',
    'news.read-more' => 'Read more',
    'news.article.published' => 'Article published on %2 by %1',

    'staff' => 'Staff',

    'user.last-online' => 'Last seen online on %1',
    'user.my-page' => 'My page',
    'user.logout' => 'Log out',
    'user.online' => 'Online',
    'user.offline' => 'Offline',

    'user.settings' => 'Settings',
    'user.settings.my-preferences' => 'My preferences',
    'user.settings.my-password' => 'My password',
    'user.settings.my-email' => 'My e-mail address',
    'user.settings.change-password' => 'Change password',
    'user.settings.change-email' => 'Change e-mail address',
    'user.settings.e-mail' => 'E-mail address',
    'user.settings.change-email.description' => 'Want to change your e-mail address?',
    'user.settings.my-status' => 'My status',
    'user.settings.my-status.description' => 'What is your status?',
    'user.settings.online-status' => 'Online status',
    'user.settings.online-status.description' => 'Who can see you are online?',
    'user.settings.online-status.everybody' => 'Everybody',
    'user.settings.online-status.nobody' => 'Nobody',
    'user.settings.friends-follow' => 'Friends follow',
    'user.settings.friends-follow.description' => 'Can friends follow you in the hotel?',
    'user.settings.friends-follow.yes' => 'Yes, that\'s okay',
    'user.settings.friends-follow.no' => 'No, please not',
    'user.settings.change-my-password' => 'Change my password',
    'user.settings.change-my-password.description' => 'Are you afraid someone knows your password? Change it here.',
    'user.settings.current-password' => 'Current password',
    'user.settings.new-email' => 'Your new e-mail address',
    'user.settings.new-email-repeat' => 'Your new e-mail address (repeat)',
    'user.settings.new-password' => 'Your new password',
    'user.settings.new-password-repeat' => 'Your new password (repeat)',
    'user.settings.save' => 'Save',
    'user.settings.error.email-incorrect' => 'This is not a valid e-mail address.',
    'user.settings.error.password-incorrect' => 'The entered password is incorrect.',
    'user.settings.error.passwords-dont-match' => 'The entered passwords don\'t match.',
    'user.settings.error.password-too-short' => 'The entered password is too short.',
    'user.settings.error.emails-dont-match' => 'The entered e-mail addresses don\'t match.',
    'user.settings.success.preferences-changed' => 'Your preferences were updated!',
    'user.settings.success.email-changed' => 'Your e-mail address was updated!',
    'user.settings.success.password-changed' => 'Your password was updated!',

    'community' => 'Community',
    'community.staff' => 'Staff members',
    'community.staff.staff-on-hotel' => 'Staff on %1',
    'community.richest-members' => 'Richest members',
    // 'community.staff.staff-on-hotel.description' => ''

    'admin' => 'Housekeeping',
    'admin.settings' => 'Settings',
    'admin.settings.cms' => 'CMS Settings',
    'admin.settings.client' => 'Client Settings',
    'admin.settings.plugin' => 'Plugin Settings',
    'admin.settings.setting.base_url' => 'Site Base URL',
    'admin.settings.setting.hotel_name' => 'Hotel Name',
    'admin.settings.setting.hotel_slogan' => 'Hotel Slogan',
    'admin.settings.setting.language' => 'Language',
    'admin.settings.setting.logo_url' => 'Logo URL',
    'admin.settings.setting.password_min_length' => 'Minimum password length',
    'admin.settings.setting.skin' => 'CMS Skin',
    'admin.settings.save' => 'Save settings!',
    'admin.news' => 'News',
    'admin.news.new-article' => 'Write new article',
    'admin.news.title' => 'Title',
    'admin.news.lead' => 'Lead',
    'admin.news.message' => 'Full message',
    'admin.news.image' => 'Image',
    'admin.news.publish' => 'Publish!',
    'admin.users' => 'Users',
];
