<?php

$lang = [
    'translation.language' => 'Nederlands',
    'translation.translator' => 'Xesau',
    'translation.translator.url' => 'https://uhabbo.xesau.eu',
    'translation.last-updated' => 'August 24th 2015',

    'error.page-not-found' => 'Pagina niet gevonden',
    'error.page-not-found.description' => 'De opgevraagde pagina kon niet worden gevonden.',
    'error.no-access' => 'Geen toegang',
    'error.no-access.description' => 'Je hebt toegang (meer) tot deze pagina.',
    'error.return-to-home' => 'Keer terug naar de homepagina',

    'error.login.login' => 'Er is geen account met deze gebruikersnaam of dit e-mailadres',
    'error.login.password' => 'Het ingevoerde wachtwoord klopt niet',
    'error.login.banned' => 'Dit account is verbannen. Reden: %1',
    'error.login.blocked' => 'De inlogpoging werd geblokkeerd.',

    'error.register.username.legnth' => 'Je gebruikersnaam moet minstens 3 tekens en maximaal 20 tekens lang zijn.',
    'error.register.username.not-available' => 'Deze gebruikersnaam is niet meer beschikbaar',
    'error.register.password.length' => 'Je wachtwoord moet minstens 8 tekens lang zijn',
    'erorr.register.password.dont-match' => 'De opgegeven wachtwoorden komen niet overeen.',
    'error.register.email.not-available' => 'Er is al een account met dit e-mailadres',
    'error.register.email.format' => 'Dit e-mailadres is niet goed.',
    'error.register.blocked' => 'De registartiepoging werd geblokkeerd.',

    'general.advertisement' => 'Advertentie',
    'general.users-online' => 'Er zijn %1 spelers online!',
    'general.welcome' => 'Welkom op %1',
    'general.register-now' => 'Registreer je nu op %1',
    'general.enter-hotel' => 'Ga in %1',
    'general.logged-out' => 'Je bent uitgelogd! Tot ziens.',
    'general.welcome-back' => 'Welkom terug, %1',

    'login' => 'Inloggen',
    'login.username-or-email' => 'Gebruikersnaam of e-mail',
    'login.password' => 'Wachtwoord',
    'login.remember-me' => 'Onthoud mij',
    'login.submit' => 'Inloggen!',

    'register' => 'Registreren',
    'register.login', 'Heb je al een account?',
    'register.username' => 'Gebruikersnaam',
    'register.email' => 'E-mailadres',
    'register.password' => 'Wachtwoord',
    'register.password-repeat' => 'Wachtwoord (herhalen)',
    'register.captcha' => 'Ik ben geen robot:',
    'register.submit' => 'Registreren!',
    'register.account-created' => 'Gefeliciteerd! Je account is aangemaakt. Controller je e-mail op het activatiebericht. TIP: Kijk ook in je spam/junk.',
    'register.account-created.title' => 'Je account op %1 is aangemaakt',
    'register.account-created.message' => "Beste %1,\r\n\r\nJe account op %3 is aangemaakt.\r\nVoordat je kunt inloggen, moet je account nog geactiveerd worden. Zo weten we zeker"
            . " dat dit e-mailadres geldig is. Je kunt je account activeren door op de volgende link te klikken:\r\n\%2\r\n\r\nMet vriendelijke groet\r\nHet team van %3",

    'news' => 'Nieuws',
    'news.latest-news' => 'Het laatste nieuws',
    'news.select-article' => 'Selecteer een artikel uit de lijst om te lezen',
    'news.read-more' => 'Lees meer',
    'news.article.published' => 'Artikel gepubliceerd op %2 door %1',

    'staff' => 'Medewerkers',

    'user.last-online' => 'Laatst online op %1',
    'user.my-page' => 'Mijn pagina',
    'user.logout' => 'Uitloggen',
    'user.online' => 'Online',
    'user.offline' => 'Offline',

    'user.settings' => 'Instellingen',
    'user.settings.my-preferences' => 'Mijn voorkeuren',
    'user.settings.my-password' => 'Mijn wachtwoord',
    'user.settings.my-email' => 'Mijn e-mailadres',
    'user.settings.change-password' => 'Wachtwoord veranderen',
    'user.settings.change-email' => 'E-mailadres veranderen',
    'user.settings.e-mail' => 'E-mailadres',
    'user.settings.change-email.description' => 'Wil je je e-mailadres veranderen?',
    'user.settings.my-status' => 'Mijn status',
    'user.settings.my-status.description' => 'Wat is jouw status?',
    'user.settings.online-status' => 'Onlinestatus',
    'user.settings.online-status.description' => 'Wie mag er zien dat je online bent?',
    'user.settings.online-status.everybody' => 'Iedereen',
    'user.settings.online-status.nobody' => 'Niemand',
    'user.settings.friends-follow' => 'Volgfunctie',
    'user.settings.friends-follow.description' => 'Mogen vrienden je volgen in het hotel?',
    'user.settings.friends-follow.yes' => 'Ja, geen probleem.',
    'user.settings.friends-follow.no' => 'Nee, liever niet.',
    'user.settings.change-my-password' => 'Verander mijn wachtwoord',
    'user.settings.change-my-password.description' => 'Ben je bang dat iemand je wachtwoord weet? Verander het hier.',
    'user.settings.new-email' => 'Je nieuwe e-mailadres',
    'user.settings.new-email-repeat' => 'Je nieuwe e-mailadres (herhalen)',
    'user.settings.new-password' => 'Je nieuwe wachtwoord',
    'user.settings.current-password' => 'Huidig wachtwoord',
    'user.settings.new-password-repeat' => 'Je nieuwe wachtwoord (repeat)',
    'user.settings.save' => 'Opslaan',
    'user.settings.error.email-incorrect' => 'Dit is geen geldig e-mailadres.',
    'user.settings.error.password-incorrect' => 'Het ingevoerde wachtwoord is incorrect.',
    'user.settings.error.passwords-dont-match' => 'De ingevoerde wachtwoorden komen niet overeen.',
    'user.settings.error.password-too-short' => 'Het ingevoerde wachtwoord is te kort.',
    'user.settings.error.emails-dont-match' => 'De ingevoerde e-mailadressen komen niet overeen.',
    'user.settings.success.preferences-changed' => 'Je voorkeuren zijn opgeslagen!',
    'user.settings.success.email-changed' => 'Je e-mailadres is bijgewerkt!',
    'user.settings.success.password-changed' => 'Je wachtwoord is bijgewerkt!',

    'community' => 'Gemeenschap',
    'community.staff' => 'Medewerkers',
    'community.staff.staff-on-hotel' => 'Staff op %1',
    'community.richest-members' => 'Rijkste leden',
    'community.popular-rooms' => 'Populaire kamers',

    'admin' => 'Housekeeping',
    'admin.dashboard' => 'Dashboard',
    'admin.welcome' => 'Welkom, %1',
    'admin.settings' => 'Instellingen',

    'admin.settings.cms' => 'CMS-instellingen',
    'admin.settings.client' => 'Clientinstellingen',
    'admin.settings.plugin' => 'Plugininstellingen',
    'admin.settings.register' => 'Registratie-instellingen',
    'admin.settings.setting.base_url' => 'Sitebasis-URL',
    'admin.settings.setting.hotel_name' => 'Hotelnaam',
    'admin.settings.setting.hotel_slogan' => 'Hotelslogan',
    'admin.settings.setting.language' => 'Taal',
    'admin.settings.setting.logo_url' => 'Logo-URL',
    'admin.settings.logo-url-live-preview' => 'Live Logo Preview',
    'admin.settings.setting.password_min_length' => 'Minimum wachtwoordlengte',
    'admin.settings.setting.skin' => 'CMS-uiterlijk',
    'admin.settings.setting.maintainance' => 'Onderhoudsmodus',
    'admin.settings.setting.avatar_image_url' => 'Avatarimage-URL',
    'admin.settings.setting.client_css' => 'Client CSS-URL',
    'admin.settings.setting.client_emu_ip' => 'Emulator-IP',
    'admin.settings.setting.client_emu_port' => 'Emulatorpoort',
    'admin.settings.setting.client_js' => 'Client JS-URL',
    'admin.settings.setting.client_mus_ip' => 'Emulator-MUS-IP',
    'admin.settings.setting.client_mus_port' => 'Emulator-MUS-poort',
    'admin.settings.setting.client_swf_dir' => 'SWF-map-URL',
    'admin.settings.setting.client_swf_express' => 'expressInstall.swf-URL',
    'admin.settings.setting.client_swf_ext_texts' => 'External Flash Texts-URL',
    'admin.settings.setting.client_swf_ext_vars' => 'External Variables-URL',
    'admin.settings.setting.client_swf_habbo' => 'Habbo.swf-URL',
    'admin.settings.setting.register_activity_points' => 'Starthoeveelheid activiteitspunten',
    'admin.settings.setting.register_credits' => 'Starthoeveelheid credits',
    'admin.settings.setting.register_vip_points' => 'Starthoeveelheid VIP-punten',
    'admin.settings.setting.register_look' => 'Standaardlook',
    'admin.settings.setting.register_motto' => 'Standaardmotto',
    'admin.settings.save' => 'Instellingen opslaan!',
    'admin.settings.saved' => 'De instellingen zijn opgeslagen!',

    'admin.news' => 'Nieuws',
    'admin.news.deleted' => 'Prullenbak',
    'admin.news.success.article-published' => 'Artikel succesvol gepubliceerd!',
    'admin.news.creation-error' => 'Iets is foutgegaan tijdens het opslaan van het artikel.',
    'admin.news.edit-article' => 'Artikel bewerken: %1',
    'admin.news.new-article' => 'Nieuw artikel schrijven',
    'admin.news.title' => 'Titel',
    'admin.news.lead' => 'Lead',
    'admin.news.message' => 'Volledig bericht',
    'admin.news.image' => 'Afbeelding',
    'admin.news.image-live-preview' => 'Afbeeldingsvoorbeeld',
    'admin.news.publish' => 'Publiceren!',
    'admin.news.save' => 'Wijzigingen opslaan!',
    'admin.news.custom-image-set' => '-- Door hier een afbeelding te selecteren verlies je de huidige --',

    'admin.users-and-ranks' => 'Gebruikers en rangen',
    'admin.users.ban' => 'Ban!',
    'admin.users.edit' => 'Bewerken',

    'admin.ranks' => 'Rangen',
    'admin.banned-users' => 'Verbannen gebruikers',
    'admin.banned-ips' => 'Verbannen IP\'s',

    'admin.plugins' => 'Plugins',
    'admin.plugins.enabled-plugins' => 'Ingeschakelde plugins (%1)',
    'admin.plugins.disabled-plugins' => 'Uitgeschakelde plugins (%1)',
    'admin.plugins.edit' => 'Instellingen bewekren',
    'admin.plugins.enable' => 'Plugin inschakelen',
    'admin.plugins.disable' => 'Plugin uitschakelen',
    'admin.plugins.no-enabled' => 'Er zijn geen ingeschakelde plugins.',
    'admin.plugins.no-disabled' => 'Er zijn geen uitgeschakelede plugins.',
    'admin.plugins.success.plugin-enabled' => 'De plugin was ingeschakeld!',
    'admin.plugins.success.plugin-disabled' => 'De plugin was uitgeschakeld!',
    'admin.plugins.error.couldnt-save' => 'Er was een fout tijdens het opslaan van de plugininstellingen.',
    'admin.plugins.error.couldnt-enable' => 'Er was een fout tijdens het inschakelen van de plugin.',
    'admin.plugins.error.couldnt-disnable' => 'Er was een fout tijdens het uitschakelen van de plugin.',
    'admin.plugins.no-settings' => 'Deze plugin heeft geen instellingen.',
    'admin.plugins.success.saved' => 'De plugininstellingen zijn opgeslagen!',

    'admin.pages' => 'Pagina\'s',
    'admin.pages.edit' => 'Pagina bewerken: %1',
    'admin.pages.create-page' => 'Pagina aanmaken',
    'admin.pages.name' => 'Paginanaam',
    'admin.pages.no-pages' => 'Je hebt nog geen pagina\'s aangemaakt.',
    'admin.pages.no-pages.description' => 'Om een pagina aan te maken, klik op de knop hieronder.',
    'admin.pages.access-level' => 'Toegnagsniveau',
    'admin.pages.access-level.all' => 'Iedereen',
    'admin.pages.access-level.guest' => 'Enkel gasten',
    'admin.pages.access-level.user' => 'Geregistreerde gebruikers',
    'admin.pages.access-level.mod' => 'Moderatoren',
    'admin.pages.access-level.admin' => 'Administratoren',
    'admin.pages.add-column' => 'Kolom toevoegen',
];
