<?php

$lang = [
    'translation.language' => 'Português',
    'translation.translator' => 'Helpi',
    'translation.translator.url' => 'http://hebbohotel.com.br/helpi',
    'translation.last-updated' => '22 de Setembro de 2015',

    'error.page-not-found' => 'Página não Encontrada',
    'error.page-not-found.description' => 'A página solicitada não pôde ser encontrada.',
    'error.no-access' => 'Sem Acesso',
    'error.no-access.description' => 'Você não tem acesso a esta página.',
    'error.return-to-home' => 'Retorne para a Página Inicial.',

    'error.login.login' => 'Não existe nenhuma conta com esse nome de usuário ou e-mail.',
    'error.login.password' => 'A senha digitada está incorreta.',
    'error.login.banned' => 'Esta conta foi banida. Razão: %1',
    'error.login.blocked' => 'A tentativa de login foi bloqueada.',

    'error.register.username.legnth' => 'Seu nome de usuário deve ser no mínimo 3 caracteres e não pode ser maior do que 20.',
    'error.register.username.not-available' => 'Este nome de usuário não está mais disponível.',
    'error.register.password.length' => 'Sua senha deve ter pelo menos 8 caracteres.',
    'error.register.password.dont-match' => 'As senhas digitadas não correspondem',
    'error.register.email.not-available' => 'Já existe uma conta com este endereço de e-mail.',
    'error.register.email.format' => 'Este endereço de e-mail não é válido.',
    'error.register.blocked' => 'Esta tentativa de registro foi bloqueada.',

    'general.advertisement' => 'Anúncio',
    'general.users-online' => 'Temos %1 user(s) Jogando!',
    'general.welcome' => 'Bem-Vindo ao %1',
    'general.register-now' => 'Registre-se agora no  %1',
    'general.enter-hotel' => 'Jogar %1!',
    'general.logged-out' => 'Você foi desconectado! Volte mais vezes :)',
    'general.welcome-back' => 'Bem-vindo de volta, %1',
    'general.bar-community' => 'Comunidade',

    'login' => 'Crie seu Habbo, construa seu quarto, converse e faça novos amigos!',
    'login.username-or-email' => 'Nome de Usuário ou e-mail',
    'login.password' => 'Senha',
    'login.remember-me' => 'Lembrar-me',
    'login.submit' => 'Conectar!',

    'register' => 'Registro',
    'register.login' => 'Já tem uma conta?',
    'register.username' => 'Nome de Usuário',
    'register.email' => 'E-mail',
    'register.password' => 'Senha',
    'register.password-repeat' => 'Senha (repita)',
    'register.captcha' => 'I am not a robot:',
    'register.submit' => 'Register!',
    'register.account-created' => 'Parabéns! Sua conta foi criada. Mas precisamos que logue novamente em sua conta, por questão apenas de segurança :)',

    'news' => 'Notícias',
    'news.latest-news' => 'Últimas Notícias',
    'news.select-article' => 'Selecione um artigo a partir da lista para ler',
    'news.select-article-body' => 'Você não selecionou nenhuma notícia! Selecione alguma ao seu lado esquerdo para poder ler ;)',
    'news.read-more' => 'Leia Mais',
    'news.article.published' => 'Artigo publicado em %1',

    'staff' => 'Staff',

    'user.last-online' => 'Sua Última Visita foi %1',
    'user.my-page' => 'Minha Página',
    'user.logout' => 'Sair',
    'user.online' => 'Online',
    'user.offline' => 'Offline',
    'user.badges' => 'Meus Emblemas',
    'user.no-badges' => 'Pooxa, parece que eu ainda não tenho Emblemas... :(',
    'user.rooms' => 'Meus Quartos',
    'user.no-rooms' => 'Pooxa, parece que eu ainda não tenho Quartos... :(',

    'user.settings' => 'Minha Conta',
    'user.settings.my-preferences' => 'Minhas Preferências',
    'user.settings.my-password' => 'Minha Senha',
    'user.settings.my-email' => 'Meu E-mail',
    'user.settings.change-password' => 'Mudar Senha',
    'user.settings.change-email' => 'Mudar E-mail',
    'user.settings.e-mail' => 'E-mail',
    'user.settings.change-email.description' => 'Quer mudar o seu endereço de e-mail?',
    'user.settings.my-status' => 'Minha Missão',
    'user.settings.my-status.description' => 'Qual é a sua missão?',
    'user.settings.online-status' => 'Online',
    'user.settings.online-status.description' => 'Quem pode ver que você está online?',
    'user.settings.online-status.everybody' => 'Todos',
    'user.settings.online-status.nobody' => 'Ninguém',
    'user.settings.friends-follow' => 'Seguir',
    'user.settings.friends-follow.description' => 'Amigos podem segui-lo no hotel?',
    'user.settings.friends-follow.yes' => 'Sim, tudo bem',
    'user.settings.friends-follow.no' => 'Não, por favor, não',
    'user.settings.change-my-password' => 'Alterar minha senha',
    'user.settings.change-my-password.description' => 'Você está com medo que alguém sabe sua senha? Mude-a aqui.',
    'user.settings.current-password' => 'Senha atual',
    'user.settings.new-email' => 'O seu novo endereço de e-mail',
    'user.settings.new-email-repeat' => 'O seu novo endereço de e-mail (repita)',
    'user.settings.new-password' => 'Sua nova senha',
    'user.settings.new-password-repeat' => 'Sua nova senha (repita)',
    'user.settings.save' => 'Salvar',
    'user.settings.error.email-incorrect' => 'Este não é um endereço de e-mail válido.',
    'user.settings.error.password-incorrect' => 'A antiga senha digitada está incorreta.',
    'user.settings.error.passwords-dont-match' => 'As senhas digitadas não correspondem.',
    'user.settings.error.password-too-short' => 'A senha digitada é muito curta.',
    'user.settings.error.emails-dont-match' => 'Os emails informados não correspondem.',
    'user.settings.success.preferences-changed' => 'Suas preferências foram atualizadas!',
    'user.settings.success.email-changed' => 'O seu endereço de e-mail foi atualizado!',
    'user.settings.success.password-changed' => 'Sua senha foi atualizada!',

    'community' => 'Comunidade',
    'community.staff' => 'Nossa Equipe',
    'community.staff.staff-on-hotel' => 'Staffs do %1',
    'community.staff.staff-on-hotel.description' => 'Estamos prontos para lhes ajudar com qualquer dúvida, problema, bug ou coisas desse tipo. Mas se acaso necessitar de ajuda imediata, nossos Ajudantes estão sempre de prontidão para que possa lhes ajudar. ',
    'community.richest-members' => 'Membros mais Ricos',
    'community.popular-rooms' => 'Quartos Populares',

    'admin' => 'Housekeeping',
    'admin.dashboard' => 'Painel de Controle',
    'admin.welcome' => 'Bem-Vindo, %1',
    'admin.settings' => 'Mudanças',

    'admin.dashboard.description' => 'Este é o mais novo Painel de Controle do Hebbo Hotel!. Nele há as mais variadas ferramentas para facilitar o trabalho de nossos Staffs... Mas lembrando que ainda se encontra em construção nosso querido Painel! Então quaisquer Bug\'s ou Erros que encontrarem, reporte para um CEO!',
    'admin.dashboard.newest-users' => 'Novos Usuários',

    'admin.settings.cms' => 'Configurações da CMS',
    'admin.settings.client' => 'Configurações do Client',
    'admin.settings.plugin' => 'Configurações de Plugin',
    'admin.settings.register' => 'Configurações do Registro',
    'admin.settings.setting.base_url' => 'URL do Hotel',
    'admin.settings.setting.hotel_name' => 'Nome do Hotel',
    'admin.settings.setting.hotel_slogan' => 'Slogan do Hotel',
    'admin.settings.setting.language' => 'Idioma',
    'admin.settings.setting.logo_url' => 'URL da Logo',
    'admin.settings.logo-url-live-preview' => 'Prévia da Logo',
    'admin.settings.setting.password_min_length' => 'Comprimento mínimo de senha',
    'admin.settings.setting.skin' => 'Tema da CMS',
    'admin.settings.setting.maintainance' => 'Manutenção?',
    'admin.settings.setting.avatar_image_url' => 'URL do Avatar Image',
    'admin.settings.setting.client_css' => 'URL do CSS',
    'admin.settings.setting.client_emu_ip' => 'IP do Emulador',
    'admin.settings.setting.client_emu_port' => 'Porta do Emulador',
    'admin.settings.setting.client_js' => 'URL do JS',
    'admin.settings.setting.client_mus_ip' => 'MUS IP Emulador',
    'admin.settings.setting.client_mus_port' => 'Porta MUS do Emulador',
    'admin.settings.setting.client_swf_dir' => 'Diretório da SWF',
    'admin.settings.setting.client_swf_express' => 'URL do expressInstall.swf',
    'admin.settings.setting.client_swf_ext_texts' => 'External Flash Texts',
    'admin.settings.setting.client_swf_ext_vars' => 'External Variables',
    'admin.settings.setting.client_swf_habbo' => 'Habbo.swf',
    'admin.settings.setting.register_activity_points' => 'Rosquinhas Iniciais',
    'admin.settings.setting.register_credits' => 'Moedas a Iniciais',
    'admin.settings.setting.register_vip_points' => 'Diamantes a Iniciais',
    'admin.settings.setting.register_look' => 'Visual Inicial',
    'admin.settings.setting.register_motto' => 'Missão Inicial',
    'admin.settings.save' => 'Salvar Mudanças',
    'admin.settings.saved' => 'As mudanças foram Salvas!',

    'admin.news' => 'Notícias',
    'admin.news.deleted' => 'Notícias Deletadas',
    'admin.news.success.published' => 'Notícia Publicada com Sucesso!',
    'admin.news.success.updated' => 'Notícia Editada com Sucesso!',
    'admin.news.success.moved-to-trash' => 'Notícia Movida para Lixeira!',
    'admin.news.success.deleted' => 'Notícia Deletada permanentemente com Sucesso',
    'admin.news.error.couldnt-create' => 'Algo de errado aconteceu ao Publicar a Notícia.',
    'admin.news.edit-article' => 'Editar Notícia: %1',
    'admin.news.new-article' => 'Nova Notícia',
    'admin.news.title' => 'Título',
    'admin.news.lead' => 'Prévia',
    'admin.news.message' => 'História',
    'admin.news.image' => 'Imagem',
    'admin.news.image-live-preview' => 'Prévia da Imagem',
    'admin.news.publish' => 'Publicar!',
    'admin.news.save' => 'Salvar Modificações!',

    'admin.users-and-ranks' => 'Users & Ranks',
    'admin.users.ban' => 'Ban!',
    'admin.users.edit' => 'Editar Usuário',

    'admin.banned-users' => 'Usuários Banidos',
    'admin.banned-ips' => 'IPs Banidos',

    'admin.plugins' => 'Plugins',
    'admin.plugins.enabled-plugins' => 'Plugins ativados (%1)',
    'admin.plugins.disabled-plugins' => 'PLugins desativados (%1)',
    'admin.plugins.edit' => 'Editar',
    'admin.plugins.disable' => 'Desativar',
    'admin.plugins.enable' => 'Ativar',
    'admin.plugins.no-enabled' => 'Não há nenhum Plugin Ativado',
    'admin.plugins.no-disabled' => 'Não há nenhum Plugin Desativado',
    'admin.plugins.success.plugin-enabled' => 'O Plugin foi Ativado',
    'admin.plugins.plugin-disabled' => 'O Plugin foi Desativado',
    'admin.plugins.no-settings' => 'Este plugin não define quaisquer mudanças',
    'admin.plugins.success.saved' => 'As configurações foram salvas',
    'admin.plugins.couldnt-save' => 'Houve um erro ao salvar as configurações',
];
