<?php

$lang = [
 'error.page-not-found' => 'Страница не найдена',
 'error.page-not-found.description' => 'Запрашиваемая страница не найдена.',
 'error.no-access' => 'Нет доступа',
 'error.no-access.description' => 'Вы (больше) не имеете доступа к этой странице.',
 'error.return-to-home' => 'Вернуться на главную страницу.',

 'error.login.login' => 'Там нет счета в этом пользователя или адрес электронной почты.',
 'error.login.password' => 'Введенный пароль неверен.',
 'error.login.banned' => 'Этот аккаунт был запрещен. причина: %1',
 'error.login.blocked' => 'Войти попытка была заблокирована.',

 'error.register.username.legnth' => 'Ваше имя пользователя должно быть по крайней мере 3 символов и не может быть длиннее, чем 20.',
 'error.register.username.not-available' => 'Это имя пользователя больше не доступен.',
 'error.register.password.length' => 'Ваш пароль должен быть длиной не менее 8 символов.',
 'error.register.email.not-available' => 'Существует уже аккаунт с таким адресом электронной почты.',
 'error.register.email.format' => 'Этот адрес электронной почты не является действительным.',

 'general.advertisement' => 'Реклама',
 'general.users-online' => 'Есть %1 игроков онлайн!',
 'general.welcome' => 'Добро пожаловать в %1',
 'general.register-now' => 'Зарегистрируйтесь сейчас на %1',
 'general.enter-hotel' => 'Войти в %1!',
 'general.logged-out' => 'Вы вышли! До Свидания.',
 'general.welcome-back' => 'Добро пожаловать, %1',

 'login' => 'Войти',
 'login.username-or-email' => 'Имя пользователя или адрес электронной почты',
 'login.password' => 'Пароль',
 'login.remember-me' => 'Запомни меня',
 'login.submit' => 'Войти!',

 'register' => 'Регистр',
 'register.username' => 'Имя пользователя',
 'register.email' => 'Адрес электронной почты',
 'register.password' => 'Пароль',
 'register.password-repeat' => 'Пароль (повтор)',
 'register.captcha' => 'Я не робот:',
 'register.submit' => 'Регистр!',
 'register.account-created' => 'Поздравления! Ваш аккаунт был создан. Проверьте вашу электронную почту для сообщения активации. СОВЕТ: Взгляните на папку спам / нежелательной тоже.',
 'register.account-created.title' => 'Ваш аккаунт на %1 был создан.',
 'register.account-created.message' => "Уважаемые %1,\r\n\r\nВаш аккаунт на %3 был создан.\r\nПрежде чем вы сможете войти, ваш аккаунт должен быть активирован первым. Таким образом, мы уверены,"
     . " этот адрес электронной почты является действительным. Вы можете активировать свою учетную запись, нажав на следующую ссылку:\r\n\%2\r\n\r\nС уважением\r\nThe %3 team",

 'news' => 'Новости',
 'news.latest-news' => 'Последние новости',
 'news.select-article' => 'Выберите статью из списка для чтения',
 'news.read-more' => 'Прочитайте больше',
 'news.article.published' => 'Статья опубликована на %2 от %1',

 'staff' => 'Персонал',

 'user.last-online' => 'Последний раз его видели онлайн на %1',
 'user.my-page' => 'Моя страница',
 'user.logout' => 'Выйти',
 'user.online' => 'Онлайн',
 'user.offline' => 'Оффлайн',

 'user.settings' => 'Настройки',
 'user.settings.my-preferences' => 'Мои предпочтения',
 'user.settings.my-password' => 'Мой пароль',
 'user.settings.my-email' => 'Мой адрес электронной почты',
 'user.settings.change-password' => 'Изменить пароль',
 'user.settings.change-email' => 'Изменить адрес электронной почты',
 'user.settings.e-mail' => 'Адрес электронной почты',
 'user.settings.change-email.description' => 'Хотите изменить свой электронный адрес?',
 'user.settings.my-status' => 'Мой статус',
 'user.settings.my-status.description' => 'Ваш статус?',
 'user.settings.online-status' => 'Онлайн статус',
 'user.settings.online-status.description' => 'Кто может видеть вы онлайн?',
 'user.settings.online-status.everybody' => 'Все',
 'user.settings.online-status.nobody' => 'Никто',
 'user.settings.friends-follow' => 'Друзья следовать',
 'user.settings.friends-follow.description' => 'Могут друзья следовать за вами в отеле?',
 'user.settings.friends-follow.yes' => 'Да, это нормально',
 'user.settings.friends-follow.no' => 'Нет, пожалуйста, не',
 'user.settings.change-my-password' => 'Изменить пароль',
 'user.settings.change-my-password.description' => 'Боитесь ли вы кто-то знает ваш пароль? Изменить его здесь.',
 'user.settings.current-password' => 'Текущий пароль',
 'user.settings.new-email' => 'Ваш новый адрес электронной почты',
 'user.settings.new-email-repeat' => 'Ваш новый адрес электронной почты (повтор)',
 'user.settings.new-password' => 'Ваш новый пароль',
 'user.settings.new-password-repeat' => 'Ваш новый пароль (повтор)',
 'user.settings.save' => 'Сохранить',
 'user.settings.error.email-incorrect' => 'Это не правильный адрес электронной почты.',
 'user.settings.error.password-incorrect' => 'Введенный пароль неверен.',
 'user.settings.error.passwords-dont-match' => 'Введенные пароли не совпадают.',
 'user.settings.error.password-too-short' => 'Введенный пароль слишком короткий.',
 'user.settings.error.emails-dont-match' => 'Введенные адреса электронной почты не совпадают.',
 'user.settings.success.preferences-changed' => 'Ваши предпочтения были обновлены!',
 'user.settings.success.email-changed' => 'Ваш адрес электронной почты был обновлен!',
 'user.settings.success.password-changed' => 'Ваш пароль был обновлен!',

 'community' => 'Общение',
 'community.staff' => 'Персональные сотрудники',
 'community.staff.staff-on-hotel' => 'Персонал на %1',
 'community.richest-members' => 'Самые богатые члены',
 // 'community.staff.staff-on-hotel.description' => ''

 'admin' => 'Домашнее хозяйство',
 'admin.settings' => 'Настройки',
 'admin.settings.cms' => 'Настройки CMS',
 'admin.settings.client' => 'Настройки клиента',
 'admin.settings.plugin' => 'Плагин Настройки',
 'admin.settings.setting.base_url' => 'Базовый URL сайта',
 'admin.settings.setting.hotel_name' => 'Название отеля',
 'admin.settings.setting.hotel_slogan' => 'Отель Слоган',
 'admin.settings.setting.language' => 'Язык',
 'admin.settings.setting.logo_url' => 'URL логотипа',
 'admin.settings.setting.password_min_length' => 'Минимальная длина пароля',
 'admin.settings.setting.skin' => 'CMS Skin',
 'admin.news' => 'Новости',
 'admin.news.new-article' => 'Написать новые новости',
 'admin.news.title' => 'Название',
 'admin.news.lead' => 'Вести',
 'admin.news.message' => 'Полное сообщение',
 'admin.news.image' => 'Изображение',
 'admin.news.publish' => 'Опубликовать!',
 'admin.users' => 'Люди',
];
