<?php

$lang = [
    'translation.language' => 'Swedish, unchecked version.',
    'translation.translator' => 'Funsolit',
    'translation.translator.url' => 'https://forum.ragezone.com/members/1333395141.html',
    'translation.last-updated' => 'August 23th 2015',

    'error.page-not-found' => 'Sidan hittades inte',
    'error.page-not-found.description' => 'Sidan som efterfrågats hittades inte.',
    'error.no-access' => 'Du har inte tillgång',
    'error.no-access.description' => 'Du har inte tilllgång till sidan (längre).',
    'error.return-to-home' => 'Återgå till hemsidan.',

    'error.login.login' => 'Det finns inget konto med detta användarnamn eller e-postadress.',
    'error.login.password' => 'Lösenordet du skrev stämmer inte.',
    'error.login.banned' => 'Användaren är portad. Skäl för portningen: %1',
    'error.login.blocked' => 'Inloggnings försöket blockerades.',

    'error.register.username.legnth' => 'Ditt användarnamn måste minst innehålla 3 tecken och inte mer än 20.',
    'error.register.username.not-available' => 'Användarnamnet är inte tillgängligt.',
    'error.register.password.length' => 'Ditt lösenord måste vara minst 5 tecken långt.',
    'error.register.password.dont-match' => 'Lösenordet du skrev stämmer inte.',
    'error.register.email.not-available' => 'Det finns redan ett konto med e-postadressen du skrev.',
    'error.register.email.format' => 'E-mailadressen är falsk eller inaktiv.',
    'error.register.blocked' => 'Registrerings försöket blockerades.',

        'general.richest-users' => 'Rikaste spelarna',
        'general.rooms-on-hotel' =>'Aktiva rum',
    'general.advertisement' => 'Advertisement',
    'general.users-online' => 'Det är %1 spelare inloggade!',
    'general.welcome' => 'Welcome to %1',
    'general.register-now' => 'Registrera nu på %1',
    'general.enter-hotel' => '%1 entré!',
    'general.logged-out' => 'Du är nu utloggad! Välkommen åter.',
    'general.welcome-back' => 'Välkommen tillbaks, %1',

    'login' => 'Logga in',
    'login.username-or-email' => 'Användarnamn eller e-mail',
    'login.password' => 'Lösenord',
    'login.remember-me' => 'Komihåg mig',
    'login.submit' => 'Logga in!',

    'register' => 'Registrera',
    'register.login' => 'Jag har redan ett konto',
    'register.username' => 'Användarnamn',
    'register.email' => 'E-mail address',
    'register.password' => 'Lösenord',
    'register.password-repeat' => 'Bekräfta ditt lösenord',
    'register.captcha' => 'Jag är ingen robot:',
    'register.submit' => 'Skapa kontot!',
    'register.account-created' => 'Grattis! Ditt konto har skapats. Kolla in din e-postadress inkorg/skräp meddelanden för att aktivera ditt konto',
    'register.account-created.title' => 'Ditt %1 konto har skapats',
         'register.account-created.message' => "Kära %1,\r\n\r\nDitt %3 har skapats.\r\nInnan du kan logga in måste du aktivera ditt konto."
      . " du aktiverar ditt konto genom att trycka på följande länken:\r\n\%2\r\n\r\nSincerely\r\Mvh %3",

    'news' => 'Nyheter',
    'news.latest-news' => 'De senaste nyheterna',
    'news.select-article' => 'Välj en artikel från listan för att läsa in den',
    'news.read-more' => 'Läs mer',
    'news.article.published' => 'Artikeln publicerades %2 av %1',

    'staff' => 'Personal',

    'user.last-online' => 'Sist inloggad %1',
    'user.my-page' => 'Min sida',
    'user.logout' => 'Logga ut',
    'user.online' => 'Aktiv på hotellet',
    'user.offline' => 'Inaktiv på hotellet',

    'user.settings' => 'Kontoinställningar',
    'user.settings.my-preferences' => 'Mina inställningar',
    'user.settings.my-password' => 'Lösenord',
    'user.settings.my-email' => 'E-postadress',
    'user.settings.change-password' => 'Ändra lösenordet',
    'user.settings.change-email' => 'Ändra e-postadressen',
    'user.settings.e-mail' => 'e-postadress',
    'user.settings.change-email.description' => 'Ändra din e-postadress',
    'user.settings.my-status' => 'Mitt motto',
    'user.settings.my-status.description' => 'Förändra ditt motto?',
    'user.settings.online-status' => 'Online status',
    'user.settings.online-status.description' => 'Vem ska kunna se om du är inloggad',
    'user.settings.online-status.everybody' => 'Alla',
    'user.settings.online-status.nobody' => 'Ingen',
    'user.settings.friends-follow' => 'Vän följning',
    'user.settings.friends-follow.description' => 'Ska dina vänner kunna följa dig?',
    'user.settings.friends-follow.yes' => 'Ja',
    'user.settings.friends-follow.no' => 'Nej',
    'user.settings.change-my-password' => 'Ändra mitt lösenord',
    'user.settings.change-my-password.description' => 'Här kan du förändra ditt lösenord.',
    'user.settings.current-password' => 'Ditt nuvarande lösenord',
    'user.settings.new-email' => 'Din nya e-postadress',
    'user.settings.new-email-repeat' => 'Din nya e-postadress (igen)',
    'user.settings.new-password' => 'Ditt nya lösenord',
    'user.settings.new-password-repeat' => 'Bekräfta ditt nya lösenord',
    'user.settings.save' => 'Spara',
    'user.settings.error.email-incorrect' => 'Detta är inte en tillgänglig e-postadress.',
    'user.settings.error.password-incorrect' => 'Lösenordet du skrev är fel.',
    'user.settings.error.passwords-dont-match' => 'Lösenordet du skrev stämmer inte.',
    'user.settings.error.password-too-short' => 'Lösenordet du skrev är för kort.',
    'user.settings.error.emails-dont-match' => 'E-postadresserna du skrev stämmer inte.',
    'user.settings.success.preferences-changed' => 'Dina inställningar uppdaterades!',
    'user.settings.success.email-changed' => 'Din e-postadress uppdaterades',
    'user.settings.success.password-changed' => 'Ditt lösenord uppdaterades!',

    'community' => 'Community',
    'community.staff' => 'Personal medlemmar',
    'community.staff.staff-on-hotel' => 'Personalen på %1',
        'community.staff.staff-on-hotel.description' => 'Personalen på %1 är vältränade inför deras jobb, de är här för att hjälpa dig som användare och även moderera hotellet.',
    'community.richest-members' => 'Rikaste användare',

    'admin' => 'Housekeeping',
    'admin.dashboard' => 'Hem',
    'admin.welcome' => 'Välkommen, %1',
    'admin.settings' => 'Inställningar',

    'admin.settings.cms' => 'CMS inställningar',
    'admin.settings.client' => 'Client inställningar',
    'admin.settings.plugin' => 'Plugin inställningar',
    'admin.settings.register' => 'Registrerings inställningar',
    'admin.settings.setting.base_url' => 'Site Base URL',
    'admin.settings.setting.hotel_name' => 'Hotell namn',
    'admin.settings.setting.hotel_slogan' => 'Hotell beskrivning',
    'admin.settings.setting.language' => 'Språk',
    'admin.settings.setting.logo_url' => 'Logo URL',
    'admin.settings.setting.password_min_length' => 'Lägsta lösenords tecken',
    'admin.settings.setting.skin' => 'CMS Skin',
    'admin.settings.setting.maintainance' => 'Maintainance inställningar',
    'admin.settings.setting.avatar_image_url' => 'Avatar bild URL',
    'admin.settings.setting.client_css' => 'Client CSS URL',
    'admin.settings.setting.client_emu_ip' => 'Emulator IP',
    'admin.settings.setting.client_emu_port' => 'Emulator Port',
    'admin.settings.setting.client_js' => 'Client JS URL',
    'admin.settings.setting.client_mus_ip' => 'Emulator MUS IP',
    'admin.settings.setting.client_mus_port' => 'Emulator MUS Port',
    'admin.settings.setting.client_swf_dir' => 'SWF direcotry URL',
    'admin.settings.setting.client_swf_express' => 'expressInstall.swf URL',
    'admin.settings.setting.client_swf_ext_texts' => 'External Flash Texts URL',
    'admin.settings.setting.client_swf_ext_vars' => 'External Variables URL',
    'admin.settings.setting.client_swf_habbo' => 'Habbo.swf URL',
    'admin.settings.setting.register_activity_points' => 'Registrerings acitivity points',
    'admin.settings.setting.register_credits' => 'Registrerings mynt',
    'admin.settings.setting.register_vip_points' => 'Registrerings VIP POINTS',
    'admin.settings.setting.register_look' => 'Registrerings utséende',
    'admin.settings.setting.register_motto' => 'Registrerings motto',
    'admin.settings.save' => 'spara inställningar!',
    'admin.settings.saved' => 'Inställningarna sparades!',

    'admin.news' => 'Nyheter',
    'admin.news.success.article-published' => 'Artikeln publicerades!',
    'admin.news.creation-error' => 'Något gick fel medans artikeln skulle publiceras.',
    'admin.news.edit-article' => 'Ändra artikelne: %1',
    'admin.news.new-article' => 'Skriv en ny artikel',
    'admin.news.title' => 'Titel',
    'admin.news.lead' => 'Mini text',
    'admin.news.message' => 'Huvud texten',
    'admin.news.image' => 'bilden',
    'admin.news.image-live-preview' => 'Visa bilden',
    'admin.news.publish' => 'Publicera!',

    'admin.users' => 'Användare',
    'admin.users.ban' => 'Porta!',
    'admin.users.edit' => 'Ändra användare',

    'admin.plugins' => 'Plugins',
    'admin.plugins.enabled-plugins' => 'Aktivera plugins (%1)',
    'admin.plugins.disabled-plugins' => 'Inaktivera plugins (%1)',
    'admin.plugins.edit' => 'Ändra inställningar',
    'admin.plugins.disable' => 'Inaktivera plugin',
    'admin.plugins.enable' => 'Aktivera plugin',
    'admin.plugins.no-enabled' => 'Det finns inga aktiverade plugins',
    'admin.plugins.no-disabled' => 'Det finns inga inaktiverade plugins',
    'admin.plugins.plugin-enabled' => 'Pluginet aktiverades',
    'admin.plugins.plugin-disabled' => 'Pluginet inakiverades',
    'admin.plugins.no-settings' => 'Pluginett har inga inställningar',
    'admin.plugins.saved' => 'Inställningarna sparades',
    'admin.plugins.couldnt-save' => 'Något gick fel medans inställningarna skulle sparas',

    'admin.pages' => 'Sidor',
    'admin.pages.edit' => 'Ändra sidan: %1',
    'admin.pages.name' => 'Ändra namn',
    'admin.pages.access-level' => 'Access lvl',
    'admin.pages.access-level.all' => 'Alla',
    'admin.pages.access-level.guest' => 'Endast gäster',
    'admin.pages.access-level.user' => 'Registrerade användare',
    'admin.pages.access-level.mod' => 'Moderators',
    'admin.pages.access-level.admin' => 'Administrator',
    'admin.pages.add-column' => 'Lägg till column',
];