<?php

$lang = [
    'translation.language' => 'Türkce',
    'translation.translator' => 'Cankiee',
    'translation.translator.url' => 'http://cankiee.li',
    'translation.last-updated' => 'September 16th 2015',

    'error.page-not-found' => 'Sayfa bulunamadi',
    'error.page-not-found.description' => 'Istedigniz Sayfa bulunamadi',
    'error.no-access' => 'Giris yasaklandi',
    'error.no-access.description' => 'Istediginiz Sayfaya giris yasaklandi.',
    'error.return-to-home' => 'Sayfaya geri dön.',

    'error.login.login' => 'Verdiginiz Hesap adi veya E-posta adressi bulunamadi.',
    'error.login.password' => 'Parolaniz yanlis.',
    'error.login.banned' => 'Girişiniz yasaklandı. Sebep: %1',
    'error.login.blocked' => 'Oturum açma engellendi.',

    'error.register.username.legnth' => 'Kullanıcı adınız en az 3 karakter uzunluğunda olmalı ve max 20 karakter olmasi gerekir.',
    'error.register.username.not-available' => 'Bu kullanıcı adı artık mevcut değildir.',
    'error.register.password.length' => 'Parolanız en az 8 karakter uzunluğunda olmalıdır.',
    'error.register.password.dont-match' => 'Girilen şifreler eşleşmiyor',
    'error.register.email.not-available' => 'bu e-posta adresi baska bir hesapa sahipdir.',
    'error.register.email.format' => 'Bu e -posta adresi geçerli değil.',
    'error.register.blocked' => 'Kayıt denemesi engellendi.',

    'general.advertisement' => 'Reklam',
    'general.users-online' => '%1 Üye çevrimiçi',
    'general.welcome' => '%1'ya hoş geldin',
    'general.register-now' => 'Bugün katil (Ücretsiz)',
    'general.enter-hotel' => 'Giriş',
    'general.logged-out' => 'Başarıyla çıktınız.',
    'general.welcome-back' => 'hoş geldin, %1',

    'login' => 'Login',
    'login.username-or-email' => 'Ad veya E-posta',
    'login.password' => 'Parola',
    'login.remember-me' => 'Oturumumu açık tut',
    'login.submit' => 'Giriş!',

    'register' => 'Kayit ol',
    'register.login' => 'Bir hesabınız var mi bile?',
    'register.username' => 'Ad',
    'register.email' => 'E-posta',
    'register.password' => 'Parola',
    'register.password-repeat' => 'Parola (tekrar)',
    'register.captcha' => 'Ben bir Ro(BOT) degilim:',
    'register.submit' => 'Kayit ol!',
    'register.account-created' => 'Tebrikler! Hesapin kuruldu.',
    'register.account-created.title' => '%1 Hesapin kuruldu.',
    'register.account-created.message' => "Sevgili %1,\r\n\r\n%3 üzerinde Hesabınız oluşturuldu.\r\nGiriş önce, hesabınız öncelikle aktive edilmekdedir."
      . " Bu e-Posta adresi geçerlidir. Aşağıdaki linke tıklayarak hesabınızı aktif hale getirebilirsiniz:\r\n\%2\r\n\r\niçtenlikle\r\n%3 Ekibi",

    'news' => 'Haber',
    'news.latest-news' => 'En son Haber',
    'news.select-article' => 'Okumak için listeden bir Haber seçin',
    'news.read-more' => 'Daha fazla',
    'news.article.published' => '%2 %1 tarafindan gönderildi',

    'staff' => 'Personel',

    'user.last-online' => 'Son giriş %1',
    'user.my-page' => 'Sayfam',
    'user.logout' => 'Çıkış Yap',
    'user.online' => 'Online',
    'user.offline' => 'Offline',

    'user.settings' => 'Hesap Ayarlar',
    'user.settings.my-preferences' => 'Tercihlerim',
    'user.settings.my-password' => 'Parolam',
    'user.settings.my-email' => 'E-postam',
    'user.settings.change-password' => 'Parolami değiştir',
    'user.settings.change-email' => 'E-postami değiştir',
    'user.settings.e-mail' => 'E-posta',
    'user.settings.change-email.description' => 'Parolani mi değiştirmek istiyorsun?',
    'user.settings.my-status' => 'Benim durumum',
    'user.settings.my-status.description' => 'Durum nedir?',
    'user.settings.online-status' => 'çevrimiçi',
    'user.settings.online-status.description' => 'Çevrimiçi durumunu kimin görebileceğini seç:',
    'user.settings.online-status.everybody' => 'Herkes',
    'user.settings.online-status.nobody' => 'Hiç kimse',
    'user.settings.friends-follow' => 'Arkadastakipi',
    'user.settings.friends-follow.description' => 'Arkadaslarin seni takip edebilirmi?',
    'user.settings.friends-follow.yes' => 'Evet',
    'user.settings.friends-follow.no' => 'Hayir',
    'user.settings.change-my-password' => 'Parolanı değiştir',
    'user.settings.change-my-password.description' => 'Parolanı burdan değiştir',
    'user.settings.current-password' => 'Mevcut parola',
    'user.settings.new-email' => 'Yeni e-posta adresinizi giriniz',
    'user.settings.new-email-repeat' => 'Yeni e-posta adresinizi giriniz (tekrar)',
    'user.settings.new-password' => 'Yeni Parola',
    'user.settings.new-password-repeat' => 'Yeni Parola (tekrar)',
    'user.settings.save' => 'Kayit et',
    'user.settings.error.email-incorrect' => 'Lütfen geçerli bir eposta adresi girin.',
    'user.settings.error.password-incorrect' => 'Verdiginiz Parola yanlis.',
    'user.settings.error.passwords-dont-match' => 'Girilen şifreler eşleşmiyor.',
    'user.settings.error.password-too-short' => 'Verdiginiz Parola kisa.',
    'user.settings.error.emails-dont-match' => 'Verdiginiz e-posta adresleri eşleşmiyor.',
    'user.settings.success.preferences-changed' => 'tercihleriniz güncellendi!',
    'user.settings.success.email-changed' => 'E-posta adressiniz güncellendi!',
    'user.settings.success.password-changed' => 'Parolaniz güncellendi!',

    'community' => 'Topluluk',
    'community.staff' => 'Personel',
    'community.staff.staff-on-hotel' => 'Personel on %1',
    'community.richest-members' => 'En zengin Üyeler',
    'community.popular-rooms' => 'Sevilen Odalar',

    'admin' => 'Housekeeping',
    'admin.dashboard' => 'Anasayfa',
    'admin.welcome' => 'hoş geldin, %1',
    'admin.settings' => 'Ayarlar',

    'admin.settings.cms' => 'CMS Ayarlari',
    'admin.settings.client' => 'Client Ayarlari',
    'admin.settings.plugin' => 'Plugin Ayarlari',
    'admin.settings.register' => 'Kayit ol Ayarlari',
    'admin.settings.setting.base_url' => 'Site ana URL',
    'admin.settings.setting.hotel_name' => 'Hotel Adi',
    'admin.settings.setting.hotel_slogan' => 'Hotel Slogani',
    'admin.settings.setting.language' => 'Dil',
    'admin.settings.setting.logo_url' => 'Logo URL',
    'admin.settings.logo-url-live-preview' => 'Live Logo Preview',
    'admin.settings.setting.password_min_length' => 'En az parola uzunluğu',
    'admin.settings.setting.skin' => 'CMS Skini',
    'admin.settings.setting.maintainance' => 'Bakim modu',
    'admin.settings.setting.avatar_image_url' => 'Avatar Resim URL',
    'admin.settings.setting.client_css' => 'Client CSS URL',
    'admin.settings.setting.client_emu_ip' => 'Emulator IP',
    'admin.settings.setting.client_emu_port' => 'Emulator Port',
    'admin.settings.setting.client_js' => 'Client JS URL',
    'admin.settings.setting.client_mus_ip' => 'Emulator MUS IP',
    'admin.settings.setting.client_mus_port' => 'Emulator MUS Port',
    'admin.settings.setting.client_swf_dir' => 'SWF directory URL',
    'admin.settings.setting.client_swf_express' => 'expressInstall.swf URL',
    'admin.settings.setting.client_swf_ext_texts' => 'External Flash Texts URL',
    'admin.settings.setting.client_swf_ext_vars' => 'External Variables URL',
    'admin.settings.setting.client_swf_habbo' => 'Habbo.swf URL',
    'admin.settings.setting.register_activity_points' => 'Yeni Üyenin Pixeli',
    'admin.settings.setting.register_credits' => 'Yeni Üyenin Kredileri',
    'admin.settings.setting.register_vip_points' => 'Yeni Üyenin VIP puani',
    'admin.settings.setting.register_look' => 'Yeni Üyenin Giyimi',
    'admin.settings.setting.register_motto' => 'Yeni Üyenin Mottosu',
    'admin.settings.save' => 'Kayit et!',
    'admin.settings.saved' => 'Yeni Ayarlar kayit edilmistir!',

    'admin.news' => 'Haber',
    'admin.news.deleted' => 'Silenen Haberler',
    'admin.news.success.published' => 'Haber başarıyla yayınlandı!',
    'admin.news.success.updated' => 'Haber başarıyla güncellendi!',
    'admin.news.success.moved-to-trash' => 'Haber başarıyla çöp kutusuna taşındı.',
    'admin.news.success.deleted' => 'Haber başarıyla kalıcı olarak silindi.',
    'admin.news.error.couldnt-create' => 'Haberi tasarruf ederken bir şeyler ters gitti .',
    'admin.news.edit-article' => 'Haber düzenle: %1',
    'admin.news.new-article' => 'Yeni Haber yaz',
    'admin.news.title' => 'Haber adi',
    'admin.news.lead' => 'Öncülük',
    'admin.news.message' => 'Bütün Haber',
    'admin.news.image' => 'Resim',
    'admin.news.image-live-preview' => 'Önizleme',
    'admin.news.publish' => 'Gönder!',
    'admin.news.save' => 'Kayit et!',

    'admin.users-and-ranks' => 'Üyeler ve Ranklar',
    'admin.users.ban' => 'Ban!',
    'admin.users.edit' => 'Üye düzenle',

    'admin.ranks' => 'Ranklar',
    'admin.ranks.badge' => 'Rozet',
    'admin.ranks.name' => 'Rank adi',
    'admin.ranks.edit' => 'Rank düzenle #%1: %2',
    'admin.ranks.visibility' => 'Görünebilme',
    'admin.ranks.visible' => 'Görülebilir',
    'admin.ranks.invisible' => 'Görünemez',
    'admin.ranks.save' => 'Kayit et',
    'admin.ranks.error.couldnt-save' => 'Ranki kayit edemedik.',
    'admin.ranks.error.doesnt-exist' => 'Ranki bulamadik.',
    'admin.ranks.success.updated' => 'Rank başarıyla güncellendi.',
    'admin.banned-users' => 'Banlanan Üyeler',
    'admin.banned-ips' => 'IP Banlanan Üyeler',

    'admin.plugins' => 'Eklentiler',
    'admin.plugins.enabled-plugins' => 'Etkin Eklentileri (%1)',
    'admin.plugins.disabled-plugins' => 'Engelli Eklentileri (%1)',
    'admin.plugins.edit' => 'Ayarlari düzenle',
    'admin.plugins.disable' => 'Eklentiliyi devre dışına al',
    'admin.plugins.enable' => 'Eklentileri ac',
    'admin.plugins.no-enabled' => 'Hiçbir etkin eklentileri yok',
    'admin.plugins.no-disabled' => 'Hiçbir engelli eklentileri yok',
    'admin.plugins.plugin-enabled' => 'Eklenti etkin oldu',
    'admin.plugins.plugin-disabled' => 'Eklenti devre dışı bırakıldı',
    'admin.plugins.no-settings' => 'Bu eklenti ayarları tanımlamiyor',
    'admin.plugins.saved' => 'Ayarlar kayit edildi',
    'admin.plugins.couldnt-save' => 'Ayarları kaydedilirken bir hata oluştu',

    'admin.pages' => 'Sayfalar',
    'admin.pages.edit' => 'Sayfayi düzenle: %1',
    'admin.pages.name' => 'Sayfa adi',
    'admin.pages.no-pages' => 'You have not yet created any pages.',
    'admin.pages.access-level' => 'Erişim düzeyi',
    'admin.pages.access-level.all' => 'Herkes',
    'admin.pages.access-level.guest' => 'Sadece Misafirler',
    'admin.pages.access-level.user' => 'Kayit olan Üyeler',
    'admin.pages.access-level.mod' => 'Moderatörler',
    'admin.pages.access-level.admin' => 'Adminler',
    'admin.pages.add-column' => 'Rank ekle',
];
