<?php
$lang = [
    'translation.language' => 'Chinese',
    'translation.translator' => 's1042992',
    'translation.translator.url' => 'https://github/s1042992',
    'translation.last-updated' => 'October 29th 2018',
    'error.page-not-found' => '網頁未找到',
    'error.page-not-found.description' => '所需的頁面無法找到',
    'error.no-access' => '不可存取',
    'error.no-access.description' => '您無權訪問此頁面（不再）',
    'error.return-to-home' => '返回主頁',
    'error.login.login' => '此用戶名或電子郵件地址沒有帳戶。',
    'error.login.password' => '輸入的密碼不正確。',
    'error.login.banned' => '此帳戶已被禁止。 原因：％1',
    'error.login.blocked' => '登錄嘗試被阻止。',
    'error.register.username.legnth' => '您的用戶名必須至少為3個字符，且不得超過20個字符。',
    'error.register.username.not-available' => '此用戶名不可使用',
    'error.register.password.length' => '您的密碼長度必須至少為8個字符。
',
    'error.register.password.dont-match' => '輸入的密碼不匹配',
    'error.register.email.not-available' => '此電子郵件地址已有一個帳戶。',
    'error.register.email.format' => '此電子郵件地址無效。',
    'error.register.blocked' => '此註冊嘗試被阻止。',
    'general.advertisement' => '廣告',
    'general.users-online' => '在線有％1名玩家！',
    'general.welcome' => '歡迎來到％1',
    'general.register-now' => '立即註冊％1',
    'general.enter-hotel' => '登入%1!',
    'general.logged-out' => '你已經退出了！ 再見。',
    'general.welcome-back' => '歡迎回來, %1',
    'login' => '登入',
    'login.username-or-email' => '用戶名或電子郵件',
    'login.password' => '密碼',
    'login.remember-me' => '記住賬號',
    'login.submit' => '登入!',
    'register' => '註冊',
    'register.login' => '已經有賬戶？',
    'register.username' => '用戶名',
    'register.email' => '電子郵件地址',
    'register.password' => '密碼',
    'register.password-repeat' => '密碼再一次',
    'register.captcha' => '我不是機器人：',
    'register.submit' => '註冊!',
    'register.account-created' => '恭喜！ 您的帳號已經建立。 查看您的電子郵件以獲取激活消息。 提示：請查看您的垃圾郵件/垃圾郵件文件夾。',
    'register.account-created.title' => '您的％1帳戶已創建。',
    'register.account-created.message' => "親愛的％1，\ r \ n \ r \ \已創建您在％3上的帳戶\在您登錄之前，必須先激活您的帳戶"
      . " 此電子郵件地址有效。 您可以通過單擊以下鏈接激活您的帳戶：\ r \ n \％2 \ r \ n \ r \ n \ n \徹底\ r \ n \ n％3團隊
",
    'news' => '新聞',
    'news.latest-news' => '最新新聞',
    'news.select-article' => '從列表中選擇要閱讀的文章',
    'news.read-more' => '閱讀更多',
    'news.article.published' => '％1發布在％2上的文章',
    'staff' => '員工',
    'user.last-online' => '最後一次在線看到％1',
    'user.my-page' => '我的頁面',
    'user.logout'=>'退出'，
    'user.online'=>'在線'，
    'user.offline'=>'離線'，
    'user.settings'=>'設置'，
    'user.settings.my-preferences'=>'我的偏好'，
    'user.settings.my-password'=>'我的密碼'，
    'user.settings.my-email'=>'我的電子郵件地址'，
    'user.settings.change-password'=>'更改密碼'，
    'user.settings.change-email'=>'更改電子郵件地址'，
    'user.settings.e-mail'=>'電子郵件地址'，
    'user.settings.change-email.description'=>'想要更改您的電子郵件地址？'，
    'user.settings.my-status'=>'我的狀態'，
    'user.settings.my-status.description'=>'你的狀態是什麽？'，
    'user.settings.online-status'=>'在線狀態'，
    'user.settings.online-status.description'=>'誰能看到你在線？'，
    'user.settings.online-status.everybody'=>'每個人'，
    'user.settings.online-status.nobody'=>'沒人'，
    'user.settings.friends-follow'=>'朋友關註'，
    'user.settings.friends-follow.description'=>'朋友可以在酒店關註你嗎？'，
    'user.settings.friends-follow.yes'=>'是的，沒關系'，
    'user.settings.friends-follow.no'=>'不，請不要'，
    'user.settings.change-my-password'=>'更改我的密碼'，
    'user.settings.change-my-password.description'=>'你害怕有人知道你的密碼嗎？在這裏改變它。'，
    'user.settings.current-password'=>'當前密碼'，
    'user.settings.new-email'=>'您的新電子郵件地址'，
    'user.settings.new-email-repeat'=>'您的新電子郵件地址（重覆）'，
    'user.settings.new-password'=>'您的新密碼'，
    'user.settings.new-password-repeat'=>'您的新密碼（重覆）'，
    'user.settings.save'=>'保存'，
    'user.settings.error.email-incorrect'=>'這不是有效的電子郵件地址。'，
    'user.settings.error.password-incorrect'=>'輸入的密碼不正確。'，
    'user.settings.error.passwords-dont-match'=>'輸入的密碼不匹配。'，
    'user.settings.error.password-too-short'=>'輸入的密碼太短。'，
    'user.settings.error.emails-dont-match'=>'輸入的電子郵件地址不匹配。'，
    'user.settings.success.preferences-changed'=>'您的偏好已更新！'，
    'user.settings.success.email-changed'=>'您的電子郵件地址已更新！'，
    'user.settings.success.password-changed'=>'您的密碼已更新！'，
    'community'=>'社區'，
    'community.staff'=>'工作人員'，
    'community.staff.staff-on-hotel'=>'％1上的員工'，
    'community.richest-members'=>'最富有的成員'，
    'community.popular-rooms'=>'熱門客房'，
    'admin'=>'家政'，
    'admin.dashboard'=>'信息中心'，
    'admin.welcome'=>'歡迎，％1'，
    'admin.settings'=>'設置'，
    'admin.settings.cms'=>'CMS設置'，
    'admin.settings.client'=>'客戶端設置'，
    'admin.settings.plugin'=>'插件設置'，
    'admin.settings.register'=>'註冊設置'，
    'admin.settings.setting.base_url'=>'網站基礎網址'，
    'admin.settings.setting.hotel_name'=>'酒店名稱'，
    'admin.settings.setting.hotel_slogan'=>'Hotel Slogan'，
    'admin.settings.setting.language'=>'語言'，
    'admin.settings.setting.logo_url'=>'徽標網址'，
    'admin.settings.logo-url-live-preview'=>'實時徽標預覽'，
    'admin.settings.setting.password_min_length'=>'最小密碼長度'，
    'admin.settings.setting.skin'=>'CMS Skin'，
    'admin.settings.setting.maintainance'=>'維護模式'，
    'admin.settings.setting.avatar_image_url'=>'頭像圖片網址'，
    'admin.settings.setting.client_css'=>'客戶端CSS網址'，
    'admin.settings.setting.client_emu_ip'=>'模擬器IP'，
    'admin.settings.setting.client_emu_port'=>'仿真端口'，
    'admin.settings.setting.client_js'=>'客戶端JS網址'，
    'admin.settings.setting.client_mus_ip'=>'模擬器MUS IP'，
    'admin.settings.setting.client_mus_port'=>'模擬器MUS端口'，
    'admin.settings.setting.client_swf_dir'=>'SWF目錄網址'，
    'admin.settings.setting.client_swf_express'=>'expressInstall.swf URL'，
    'admin.settings.setting.client_swf_ext_texts'=>'外部Flash文本網址'，
    'admin.settings.setting.client_swf_ext_vars'=>'外部變量網址'，
    'admin.settings.setting.client_swf_habbo'=>'Habbo.swf網址'，
    'admin.settings.setting.register_activity_points'=>'新用戶活動點'，
    'admin.settings.setting.register_credits'=>'新用戶信用'，
    'admin.settings.setting.register_vip_points'=>'新用戶VIP積分'，
    'admin.settings.setting.register_look'=>'新用戶看'，
    'admin.settings.setting.register_motto'=>'新用戶座右銘'，
    'admin.settings.save'=>'保存設置！'，
    'admin.settings.saved'=>'設置已保存！'，
    'admin.news'=>'新聞'，
    'admin.news.deleted'=>'已刪除的文章'，
    'admin.news.success.published'=>'文章成功發布！'，
    'admin.news.success.updated'=>'文章已成功更新！'，
    'admin.news.success.moved-to-trash'=>'文章已成功移至垃圾箱。'，
    'admin.news.success.deleted'=>'文章已永久成功刪除。'，
    'admin.news.error.couldnt-create'=>'保存文章時出錯了。'，
    'admin.news.edit-article'=>'編輯文章：％1'，
    'admin.news.new-article'=>'寫新文章'，
    'admin.news.title'=>'標題'，
    'admin.news.lead'=>'領導'，
    'admin.news.message'=>'完整消息'，
    'admin.news.image'=>'圖片'，
    'admin.news.image-live-preview'=>'圖片預覽'，
    'admin.news.publish'=>'發布！'，
    'admin.news.save'=>'保存編輯！'，
    'admin.users-and-ranking'=>'用戶和排名'，
    'admin.users.ban'=>'禁令！'，
    'admin.users.edit'=>'編輯用戶'，
    'admin.ranks'=>'排名'，
    'admin.ranks.badge'=>'徽章'，
    'admin.ranks.name'=>'排名'，
    'admin.ranks.edit'=>'編輯排名＃％1：％2'，
    'admin.ranks.visibility'=>'可見性'，
    'admin.ranks.visible'=>'可見'，
    'admin.ranks.invisible'=>'隱形'，
    'admin.ranks.save'=>'保存等級'，
    'admin.ranks.error.couldnt-save'=>'無法保存排名。'，
    'admin.ranks.error.doesnt-exist'=>'無法找到等級。'，
    'admin.ranks.success.updated'=>'排名已成功更新。'，
    'admin.banned-users'=>'禁止用戶'，
    'admin.banned-ips'=>'禁止的IP'，
    'admin.plugins'=>'插件'，
    'admin.plugins.enabled-plugins'=>'啟用插件（％1）'，
    'admin.plugins.disabled-plugins'=>'已禁用的插件（％1）'，
    'admin.plugins.edit'=>'編輯設置'，
    'admin.plugins.disable'=>'禁用插件'，
    'admin.plugins.enable'=>'啟用插件'，
    'admin.plugins.no-enabled'=>'沒有啟用的插件'，
    'admin.plugins.no-disabled'=>'沒有禁用的插件'，
    'admin.plugins.plugin-enabled'=>'插件已啟用'，
    'admin.plugins.plugin-disabled'=>'該插件被禁用'，
    'admin.plugins.no-settings'=>'此插件未定義任何設置'，
    'admin.plugins.saved'=>'設置已保存'，
    'admin.plugins.couldnt-save'=>'保存設置時出錯'，
    'admin.pages'=>'頁面'，
    'admin.pages.edit'=>'編輯頁面：％1'，
    'admin.pages.name'=>'頁面名稱'，
    'admin.pages.no-pages'=>'你還沒有創建任何頁面。'，
    'admin.pages.access-level'=>'訪問級別'，
    'admin.pages.access-level.all'=>'每個人'，
    'admin.pages.access-level.guest'=>'只有客人'，
    'admin.pages.access-level.user'=>'註冊用戶'，
    'admin.pages.access-level.mod'=>'主持人'，
    'admin.pages.access-level.admin'=>'管理員'，
    'admin.pages.add-column'=>'添加列'，
];